### ISSUE TITLE
User registration crash server bug

### ISSUE THREAD

**Issue by Shadowfaxenator** [NodeBB/NodeBB#4376] opened 2016-03-18 14:37 UTC
If I try to register new user with username in cyrilic it crashes whole forum!

**Comment by Shadowfaxenator** [comment] 2016-03-18 14:41
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ServerResponse.header (/var/www/nodebb/node_modules/express/lib/response.js:718:10)
    at ServerResponse.location (/var/www/nodebb/node_modules/express/lib/response.js:835:8)
    at ServerResponse.redirect (/var/www/nodebb/node_modules/express/lib/response.js:874:8)
    at Object.helpers.redirect (/var/www/nodebb/src/controllers/helpers.js:44:7)
    at /var/www/nodebb/src/middleware/middleware.js:113:23
    at /var/www/nodebb/src/user/data.js:17:4
    at /var/www/nodebb/src/user/data.js:23:4
    at fireFilterHook (/var/www/nodebb/src/plugins/hooks.js:92:11)
    at Object.Plugins.fireHook (/var/www/nodebb/src/plugins/hooks.js:76:5)
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ServerResponse.header (/var/www/nodebb/node_modules/express/lib/response.js:718:10)
    at ServerResponse.location (/var/www/nodebb/node_modules/express/lib/response.js:835:8)
    at ServerResponse.redirect (/var/www/nodebb/node_modules/express/lib/response.js:874:8)
    at Object.helpers.redirect (/var/www/nodebb/src/controllers/helpers.js:44:7)
    at /var/www/nodebb/src/middleware/middleware.js:113:23
    at /var/www/nodebb/src/user/data.js:17:4
    at /var/www/nodebb/src/user/data.js:23:4
    at fireFilterHook (/var/www/nodebb/src/plugins/hooks.js:92:11)
    at Object.Plugins.fireHook (/var/www/nodebb/src/plugins/hooks.js:76:5)

**Comment by julianlam** [comment] 2016-03-18 14:49
Please provide the username here.

**Comment by Shadowfaxenator** [comment] 2016-03-18 17:47
I used `Шадоуфакс` But i've noticed that crash appears only when I use browser in incognito mode

**Comment by nhlpl** [comment] 2016-03-19 19:26
Confirmed.

Windows 7, Opera 35.0.2066.92, New private window
NodeBB 1.0.1 version, v1.x.x branch

Tested using `Шадоуфакс` phrase as a new username.

```
19/3 15:21 [84381] - [31merror[39m: TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
    at ServerResponse.header (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/express/lib/response.js:718:10)
    at ServerResponse.location (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/express/lib/response.js:835:8)
    at ServerResponse.redirect (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/express/lib/response.js:874:8)
    at Object.helpers.redirect (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/controllers/helpers.js:44:7)
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/middleware/middleware.js:113:23
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/user/data.js:17:4
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/user/data.js:23:4
    at fireFilterHook (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/plugins/hooks.js:92:11)
    at Object.Plugins.fireHook (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/plugins/hooks.js:76:5)
    at modifyUserData (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/user/data.js:131:11)
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/user/data.js:58:4
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/database/mongo/hash.js:136:4
    at handleCallback (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/mongodb/lib/utils.js:96:12)
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/mongodb/lib/cursor.js:848:16
    at handleCallback (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/mongodb-core/lib/cursor.js:154:5)
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
    at ServerResponse.header (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/express/lib/response.js:718:10)
    at ServerResponse.location (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/express/lib/response.js:835:8)
    at ServerResponse.redirect (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/express/lib/response.js:874:8)
    at Object.helpers.redirect (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/controllers/helpers.js:44:7)
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/middleware/middleware.js:113:23
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/user/data.js:17:4
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/user/data.js:23:4
    at fireFilterHook (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/plugins/hooks.js:92:11)
    at Object.Plugins.fireHook (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/plugins/hooks.js:76:5)
    at modifyUserData (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/user/data.js:131:11)
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/user/data.js:58:4
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/src/database/mongo/hash.js:136:4
    at handleCallback (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/mongodb/lib/utils.js:96:12)
    at /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/mongodb/lib/cursor.js:848:16
    at handleCallback (/var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo/node_modules/mongodb-core/lib/cursor.js:154:5)
19/3 15:21 [84381] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
19/3 15:21 [84381] - [32minfo[39m: [app] Database connection closed.
19/3 15:21 [84381] - [32minfo[39m: [app] Web server closed to connections.
19/3 15:21 [84381] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (84381) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
19/3 15:21 [85677] - [32minfo[39m: Time: Sat Mar 19 2016 15:21:15 GMT-0400 (EDT)
19/3 15:21 [85677] - [32minfo[39m: Initializing NodeBB v1.0.1
19/3 15:21 [85677] - [33mwarn[39m: You have no mongo password setup!
19/3 15:21 [85677] - [32minfo[39m: [database] Checking database indices.
19/3 15:21 [85677] - [33mwarn[39m: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
19/3 15:21 [85677] - [32minfo[39m: NodeBB Ready
19/3 15:21 [85677] - [32minfo[39m: Enabling 'trust proxy'
19/3 15:21 [85677] - [32minfo[39m: NodeBB is now listening on: 127.13.165.129:8080
```

**Comment by barisusakli** [comment] 2016-03-21 13:42
Seems to be fixed by https://github.com/NodeBB/NodeBB/pull/4417

**Closed by barisusakli** 2016-03-21 13:42 UTC
Labels: needs confirmation, needs more info
