### ISSUE TITLE
Error on plugin download list. Certificate Expired

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#12788] opened 2024-09-12 08:34 UTC
Hi,

When i try to open the plugin download page inside admin panel i receive an error.

If i check the log the problem is on this URL: https://packages.nodebb.org/api/v1/plugins

The certificate is expired.

**Comment by julianlam** [comment] 2024-09-12 13:50
Hello @andreadragotta! Thanks for reaching out, we're seeing similar *intermittent* issues on our end with our test runner (e.g. [this test run](https://github.com/NodeBB/NodeBB/actions/runs/10821967350/job/30025012504)).

Accessing the route directly is fine, the certificate is not expired, and indeed upon checking the server, the certificate itself has over a month left (and auto-renews, I haven't actually touched it in years).

Will have to dig into this log:

``` json
{
  ok: false,
  status: 526,
  statusCode: 526,
  statusText: '',
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
    'cf-ray': '8c1bdc1698f2cefd-SJC',
    connection: 'keep-alive',
    'content-length': '7110',
    'content-type': 'text/html; charset=UTF-8',
    date: 'Thu, 12 Sep 2024 00:42:48 GMT',
    expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    'referrer-policy': 'same-origin',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=4WCjFk2ZnLZbn6e4PCAM4f8b%2BnTyQ5uHA0DDpFUgEAHaMA74vRenrxfiKxtcBgkm8nhTnFwUM13EIZHfsX8iaUozugDYakmVfDOx3s18RbTK4%2BIXAQ4%2FTLSdNF4VWrRDvKyOzLtY"}],"group":"cf-nel","max_age":604800}',
    server: 'cloudflare',
    'x-frame-options': 'SAMEORIGIN'
  }
}
```

**Comment by fumiama** [comment] 2024-10-11 16:46
Same issue. https://packages.nodebb.org is pointing to a random site now.

<img width="1156" alt="截屏2024-10-12 上午1 45 02" src="https://github.com/user-attachments/assets/e57759fb-3dda-4285-852d-5876b75544c4">

**Comment by julianlam** [comment] 2024-10-11 17:26
We're trying to figure this out, but it is intermittent still. Neither @barisusakli nor I can reproduce this issue, and the IP is resolving correctly for us.

As far as I know it is not a misconfiguration issue as the config hasn't changed in years.

**Comment by fumiama** [comment] 2024-10-11 17:36
> We're trying to figure this out, but it is intermittent still. Neither @barisusakli nor I can reproduce this issue, and the IP is resolving correctly for us.
> 
> As far as I know it is not a misconfiguration issue as the config hasn't changed in years.

I just figured out that it's because some regions have DNS cache pollution. Here's my `nslookup packages.nodebb.org`,
```bash
Server:		2405:1206:9103:3500::3
Address:	2405:1206:9103:3500::3#53

Non-authoritative answer:
Name:	packages.nodebb.org
Address: 172.67.159.182
Name:	packages.nodebb.org
Address: 104.21.14.151
```
The real addr is `138.197.166.38`. I add it to /etc/host manually and everything goes well.

**Comment by julianlam** [comment] 2024-10-11 17:41
I don't know if there is anything we can do except wait for the cache pollution to resolve over time.

**Comment by fumiama** [comment] 2024-10-11 17:52
> I don't know if there is anything we can do except wait for the cache pollution to resolve over time.

I will reply to this issue as long as it recovers.

**Comment by julianlam** [comment] 2024-10-16 15:38
It seems this was related to an `AAAA` record that had been assigned to `packages.nodebb.org`. It is odd that this record existed as that server does not have an IPv6 address.

I have removed that record now, with a couple of additional reports that the issue is now resolved. Let me know if otherwise.

**Closed by julianlam** 2024-10-16 15:38 UTC
Labels: bug
