### ISSUE TITLE
Reloading on /recent causes content to go 100% width and duplicate on all pages

### ISSUE THREAD

**Issue by PassTheMayo** [NodeBB/NodeBB#6038] opened 2017-11-04 05:44 UTC
- **NodeBB version:** 1.6.1
- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** Redis
- **Database version:** `Redis server v=4.0.2 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=794bf66dc40b4ffd`

- **Exact steps to cause this issue:**

- **What you expected:** I expected the data to be correctly spaced between the sides of the pages, and data to be correctly shown.

- **What happened instead:** The Recent tab content is duplicating across all pages, and data is incorrectly spaced on Recent tab.

**Additional note** I might of screwed something up, so it's probably my fault. You can test it out on my website [here](https://forum.passthemayo.space/). Just head over to the Recent tab and then refresh. You can also travel to different pages and see the bug.

**EDIT:** This is exactly what is going on: https://vimeo.com/241280175

**Comment by pitaj** [comment] 2017-11-04 05:59
Looks like there's some issue with the template in your theme for the recent page. I'm going to close this issue and we can take this to https://community.nodebb.org since it's probably not a bug with NodeBB. (If it is I'll of course re-open this)

**Closed by pitaj** 2017-11-04 05:59 UTC
