### ISSUE TITLE
[Suggestion] Mail format verification

### ISSUE THREAD

**Issue by artur9010** [NodeBB/NodeBB#6647] opened 2018-07-14 13:11 UTC
- **NodeBB version:**  1.10.1
- **NodeBB git hash:** c8d3c3197ba3025ed395e400f8cb0b312fac790e

- **Database type:** mongo
- **Database version:** idk, shared hosting (mydevil.net)

- **Exact steps to cause this issue:**

- **What you expected:** Something like "Wrong email address"

- **What happened instead:** Nothing.

/register form
![obraz](https://user-images.githubusercontent.com/4835677/42724718-c65a9cf4-8777-11e8-876f-f24d53a9a7c3.png)

/admin/manage/users/latest
![obraz](https://user-images.githubusercontent.com/4835677/42724720-e404af6a-8777-11e8-95f2-1f918916cb25.png)

https://tools.ietf.org/html/rfc2822#section-3.4

**Comment by julianlam** [comment] 2018-07-26 18:38
Duplicate of #124

**Closed by julianlam** 2018-07-26 18:38 UTC
