### ISSUE TITLE
autocomplete drop-down of @mention shown during composing

### ISSUE THREAD

**Issue by pig315** [NodeBB/NodeBB#7256] opened 2019-01-16 03:32 UTC
NodeBB version: v1.11.1
Database type: mongo
plugin：nodebb-plugin-composer-redactor
The problem:

When I start writing a reply with a mention, for example, @Someone, then during my composing, the drop-down keeps on popping up even I don't use '@'.
The screenshot attached..
![image](https://user-images.githubusercontent.com/45277553/51224733-470d2f00-1982-11e9-920a-8430dfa0fdba.png)

**Comment by julianlam** [comment] 2019-01-28 19:46
Duplicate of #7309

**Closed by julianlam** 2019-01-28 19:46 UTC
