### ISSUE TITLE
new translations do not enter master

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11805] opened 2023-07-15 20:45 UTC
### NodeBB version

v3.2.2

### NodeBB git hash

562e4d6e439547167677cb6bce4743a2d1d7d77f

### Anything else?

It looks like @nodebb-misty has stopped pulling new translations from transifex to the `master` branch, only to `devlop`. The last time was [3 weeks ago](https://github.com/NodeBB/NodeBB/commit/354c2aebc50c6f4264a0a2ffa6e824a0b5c2abbb), although released since release (v3.2.2)

**Comment by julianlam** [comment] 2023-07-15 22:16
Yes, this is by design, as the patch versions contain fixes and we made the decision to restrict translations to the develop branch which can contain new features.

Otherwise you'd see unused strings in master for features that have not landed yet.

**Closed by julianlam** 2023-07-15 22:16 UTC
Labels: bug
