### ISSUE TITLE
failed to decode param

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4954] opened 2016-08-16 20:36 UTC
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
* Database (mongo or redis) and it's version. mongo 

some random error log
seems to hapen on topic with punctuation and special characters

```
16/8 08:22 [30950] - [31merror[39m: /topic/23786/no-dec%EDais-que-zaza-no-marc%F3-el-penalti
 URIError: Failed to decode param 'no-dec%EDais-que-zaza-no-marc%F3-el-penalti'
    at decodeURIComponent (native)
    at decode_param (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:557:18)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:618:15
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
16/8 09:39 [30948] - [31merror[39m: /topic/11430/hilo-de-canciones-de-rocks-no-m%F3viles
 URIError: Failed to decode param 'hilo-de-canciones-de-rocks-no-m%F3viles'
    at decodeURIComponent (native)
    at decode_param (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:557:18)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:618:15
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
16/8 10:01 [30950] - [31merror[39m: /topic/13502/cre%E9is-que-este-es-el-futuro-de-la-realidad-virtual
 URIError: Failed to decode param 'cre%E9is-que-este-es-el-futuro-de-la-realidad-virtual'
    at decodeURIComponent (native)
    at decode_param (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:557:18)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:618:15
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
16/8 11:26 [30950] - [31merror[39m: /topic/22959/ataque-epil%E9ptico
 URIError: Failed to decode param 'ataque-epil%E9ptico'
    at decodeURIComponent (native)
    at decode_param (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:557:18)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:618:15
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
16/8 15:25 [30954] - [31merror[39m: /topic/18182/p%E1gina-web-para-envolver-regalos-de-forma-original
 URIError: Failed to decode param 'p%E1gina-web-para-envolver-regalos-de-forma-original'
    at decodeURIComponent (native)
    at decode_param (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:557:18)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:618:15
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
16/8 15:53 [30950] - [31merror[39m: /topic/23691/qu%E9-calor-en-arizona
 URIError: Failed to decode param 'qu%E9-calor-en-arizona'
    at decodeURIComponent (native)
    at decode_param (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:557:18)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:618:15
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
16/8 15:59 [30954] - [31merror[39m: /topic/23565/qu%E9-camino-tomar%EDas
 URIError: Failed to decode param 'qu%E9-camino-tomar%EDas'
    at decodeURIComponent (native)
    at decode_param (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:557:18)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:618:15
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
```

Thank you!

**Comment by julianlam** [comment] 2016-08-17 16:32
> seems to hapen on topic with punctuation and special characters

Issue occurs because a topic is saved to the database without encoding (which is fine, as both Redis and MongoDB use UTF-8), but **on some environments**, of which I have not been able to determine, it encodes them incorrectly... as far as I can tell...

![selection_079](https://cloud.githubusercontent.com/assets/923011/17744597/75e2d9e2-6476-11e6-9c2e-cd5191b5aff8.png)

In google chrome, the url is not escaped at all (since there's no reason for it to be):

![selection_080](https://cloud.githubusercontent.com/assets/923011/17744626/9e4a62b0-6476-11e6-8123-4671cf84e07d.png)

Perhaps a bad browser...

**Comment by julianlam** [comment] 2016-08-17 16:36
This issue needs more info as we have never been able to reproduce it organically. You can manually trigger it by inserting a malformed url, e.g. http://exo.do/topic/23565/qu%E9-camino-tomar%EDas

However, the processing itself has been marked `wontfix` by the express team.

**Comment by exomarty** [comment] 2016-08-17 16:55
Mmm maybe this topics were imported from vbulletin when we transfered to nodebb and url was bad parsed...
I dont mind to delete them but cant access :D

**Comment by exomarty** [comment] 2016-08-17 16:56
nervermind just noticed they are not that old

**Comment by exomarty** [comment] 2016-08-17 17:01
ok i understand now, then maybe if some robot trying to access to a bad url, not sure ...

**Comment by julianlam** [comment] 2016-08-17 17:53
Upstream issue: expressjs/express#2652

**Closed** 2016-08-18 14:06 UTC
Labels: bug
