### ISSUE TITLE
Hide edit history of deleted posts

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6557] opened 2018-06-07 12:28 UTC
- **NodeBB version:** 1.9.3
- **Database type:** mongo
- **Database version:** 3.6.4
- **Exact steps to cause this issue:**
1. Create a post
2. Edit your post
3. Delete your post
- **What you expected:** I expected that the post will be shown as deleted for other users and the edit history would be hidden.
- **What happened instead:** The post is shown as deleted but it is still accessible via the edit history. Basically nullifying the effect of deleting your post. Admin and mods probably still should be able to see the edit history of the post. But normal users and guests shouldn't.

**Comment by barisusakli** [comment] 2018-06-07 15:10
dupe of https://github.com/NodeBB/NodeBB/issues/6425

**Comment by julianlam** [comment] 2018-06-07 15:11
Well this is a little different, isn't it? It's clearly a bug in that a deleted post shouldn't show the edit icon nor show edit history.

**Comment by julianlam** [comment] 2018-06-07 15:47
I've given it more thought -- your original action was correct, will make viewing post history a category-based privilege.

**Comment by Dravere** [comment] 2018-06-07 15:50
I don't think this is a duplicate. It is not about who can view the edit history. It is about if you still should be able to see the edit history when the post got deleted.

**Comment by julianlam** [comment] 2018-06-07 15:54
Good point, I seem to be confusing the two right now.

**Closed** 2018-06-11 20:45 UTC
