### ISSUE TITLE
Unable to change avatars

### ISSUE THREAD

**Issue by DRSchlaubi** [NodeBB/NodeBB#5970] opened 2017-10-08 08:21 UTC
Hey,
after I updated to the new version 1.6.0 I'm unable to chmage my Avatar when i click on the change button nothing happens
bye
Schlaubi

**Comment by barisusakli** [comment] 2017-10-08 12:03
Can you check your browser console for any errors?

**Comment by DRSchlaubi** [comment] 2017-10-08 12:09
Yes i can 

`/assets/nodebb.min.js?v=61ha3h1psfr:1 [deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
String.rtrim @ /assets/nodebb.min.js?v=61ha3h1psfr:1
/assets/src/client/account/edit.js?v=61ha3h1psfr:1 Uncaught TypeError: Cannot read property 'parse' of undefined
    at i.<anonymous> (/assets/src/client/account/edit.js?v=61ha3h1psfr:1)
    at i.onack (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.onpacket (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.<anonymous> (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.emit (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.ondecoded (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.<anonymous> (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.i.emit (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.add (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.ondata (/assets/nodebb.min.js?v=61ha3h1psfr:1)
/assets/src/client/account/edit.js?v=61ha3h1psfr:1 Uncaught TypeError: Cannot read property 'parse' of undefined
    at i.<anonymous> (/assets/src/client/account/edit.js?v=61ha3h1psfr:1)
    at i.onack (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.onpacket (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.<anonymous> (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.emit (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.ondecoded (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.<anonymous> (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.i.emit (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.add (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.ondata (/assets/nodebb.min.js?v=61ha3h1psfr:1)
/assets/src/client/account/edit.js?v=61ha3h1psfr:1 Uncaught TypeError: Cannot read property 'parse' of undefined
    at i.<anonymous> (/assets/src/client/account/edit.js?v=61ha3h1psfr:1)
    at i.onack (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.onpacket (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.<anonymous> (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.emit (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.ondecoded (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.<anonymous> (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.i.emit (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.add (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.ondata (/assets/nodebb.min.js?v=61ha3h1psfr:1)
/assets/src/client/account/edit.js?v=61ha3h1psfr:1 Uncaught TypeError: Cannot read property 'parse' of undefined
    at i.<anonymous> (/assets/src/client/account/edit.js?v=61ha3h1psfr:1)
    at i.onack (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.onpacket (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.<anonymous> (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.emit (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.ondecoded (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.<anonymous> (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.i.emit (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at a.add (/assets/nodebb.min.js?v=61ha3h1psfr:1)
    at i.ondata (/assets/nodebb.min.js?v=61ha3h1psfr:1)`

**Comment by barisusakli** [comment] 2017-10-08 12:12
@pitaj is Benchpress exposed as a global?

**Comment by pitaj** [comment] 2017-10-08 17:11
It is, though that shouldn't matter, as client/accounts/edit.js requires it through r.js

**Comment by pitaj** [comment] 2017-10-08 17:52
I _think_ I've replicated the issue and it was due to the Cropper library being used wrong after it was version bumped (I thought I tested that but I must have missed it).

Anyways, it's fixed in #5965

**Closed** 2017-10-09 15:40 UTC
Labels: bug

**Comment by DRSchlaubi** [comment] 2017-10-09 17:01
After I upgraded to your Version of NodeBB I got the same error

**Comment by pitaj** [comment] 2017-10-09 17:09
So you pulled down the master branched?

**Comment by DRSchlaubi** [comment] 2017-10-09 17:35
I pulles down https://github.com/NodeBB/NodeBB/tree/1c35213934e4c3734da34838278a6f78f591f616 this branch

**Comment by pitaj** [comment] 2017-10-09 17:36
Okay. Did you run `./nodebb build` after doing that?

**Comment by DRSchlaubi** [comment] 2017-10-09 17:42
I run `node app.js --upgrade`

**Comment by DRSchlaubi** [comment] 2017-10-09 17:46
Now i have run `node nodebb build`because I'm using windows and not linux but this don't fix my issue

**Comment by DRSchlaubi** [comment] 2017-10-09 18:31
Screenshot: https://schlb.pw/2ybN3f2

**Comment by pitaj** [comment] 2017-10-09 18:35
hmmm... something seriously weird is happening there. Can you try running

```
npm rm benchpressjs
npm i benchpressjs
```

**Comment by pitaj** [comment] 2017-10-09 18:38
BTW, `./nodebb` works on Windows, too.

**Comment by DRSchlaubi** [comment] 2017-10-09 18:40
Nope i still have this error

**Comment by pitaj** [comment] 2017-10-09 18:41
What is `npm ls benchpressjs`?

**Comment by DRSchlaubi** [comment] 2017-10-09 18:45
> c:\Users\admin\NodeBB>npm ls benchpressjs
nodebb@1.6.0 c:\Users\admin\NodeBB
`-- benchpressjs@1.1.0

**Comment by pitaj** [comment] 2017-10-09 18:46
Just want to make sure, did you run `./nodebb build` after reinstalling `benchpressjs`?

**Comment by pitaj** [comment] 2017-10-09 18:46
Also you'll need to restart nodebb

**Comment by DRSchlaubi** [comment] 2017-10-09 18:50
Yes I did

**Comment by pitaj** [comment] 2017-10-09 18:54
What version of npm? `npm -v`

**Comment by DRSchlaubi** [comment] 2017-10-09 18:55
My npm version is `3.10.10`

**Comment by DRSchlaubi** [comment] 2017-10-09 19:03
Sorry i forgot node.js version `v6.11.4`

**Comment by pitaj** [comment] 2017-10-09 19:09
Can you try deleting `build/public/nodebb.min.js`, then run `./nodebb build js`. Then check the contents of `build/public/nodebb.min.js`

**Comment by DRSchlaubi** [comment] 2017-10-09 19:14
https://pastebin.com/QzbQQfin

**Comment by pitaj** [comment] 2017-10-09 19:15
Can you try just going to the forum homepage and running this snippet again:

    require(['benchpress'], function (B) { console.log(B) })

**Comment by DRSchlaubi** [comment] 2017-10-09 19:16
Screenshot: https://schlb.pw/2ybNsxY

**Comment by pitaj** [comment] 2017-10-09 19:25
Hmmm, so it seems like something is seriously wrong with your bundle. Have you tried clearing your cache?

If this site is public, I'd like to try reproducing this myself if that's possible.

**Comment by DRSchlaubi** [comment] 2017-10-09 19:26
yeah my site is public https://forum.buildcraftrevolution.me/ so you can try that

**Comment by pitaj** [comment] 2017-10-09 19:30
I'm getting a different result when running that snippet. What browser are you using? 

I'm on Chrome 61 on Windows.

**Comment by DRSchlaubi** [comment] 2017-10-09 19:32
`Google Chrome | 61.0.3163.100 (Offizieller Build) (64-Bit) (cohort: Stable)` on windows

**Comment by pitaj** [comment] 2017-10-09 19:34
So did you try clearing your cache? Have you tried with a different browser?

**Comment by DRSchlaubi** [comment] 2017-10-09 19:36
Yes i cleard my cache and I tried to use the snippet in edge and got the same result

**Comment by pitaj** [comment] 2017-10-09 19:42
Hmmm. Well I don't know what to say, I can't reproduce _anywhere_, even on your site.
