### ISSUE TITLE
Ip ban not working

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5389] opened 2017-01-22 20:12 UTC
Please include the following information when submitting a bug report/issue:

* NodeBB version 1.4.2
* Database Mongo
* Exact steps to cause this issue
    1. I set ip ban but user is still able to navigate even after revoking session or restarting nodebb
   

Thank you!

**Comment by julianlam** [comment] 2017-01-27 19:55
Unable to reproduce locally using 127.0.0.1 (after overriding it in whitelist), or hardcoding detected client IP.

Ensure that you've added the IPv6 address for that user as well.

**Comment by exomarty** [comment] 2017-01-27 20:55
I tried with (example)
5.5.5.5
5.5.5.5/22

Tried to ban some mod user also and no luck

**Comment by nodebb-misty** [comment] 2017-02-04 08:30
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*

**Comment by exomarty** [comment] 2017-02-04 11:10
😩

**Comment by julianlam** [comment] 2017-02-08 18:43
@exomarty I think this might be a misunderstanding of how the IP blacklist works... [it only prevents them from logging in or registering](https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L66-L69), not from regular browsing.

So knowing that, can this issue be closed?

**Comment by exomarty** [comment] 2017-02-08 19:53
My banned ips been able to login ir register again without problems

**Comment by julianlam** [comment] 2017-02-08 20:26
Simply saying so doesn't make it real, I still cannot reproduce, so I will need the IP of the individual and your current ip blacklist settings.

**Comment by henrikekblad** [comment] 2017-02-09 18:57
Same here... have tried adding ip of one of our frequent spammers. They still create new accounts and post links.

Which headers are you looking at when banning? Could it be something X-Forwarded-For problem?

**Comment by julianlam** [comment] 2017-02-09 19:34
`req.ip` is the value I check, and displays 127.0.0.1 if your `X-Forwarded-For` is not set. If it is set, then it will reflect the correct IP address.

**Comment by henrikekblad** [comment] 2017-02-09 19:37
Hmm. Weird....did you ever test the functionality live on nodebb.org?

**Comment by julianlam** [comment] 2017-02-09 19:43
Yes, I am testing it on my local environment, although I just added my own IP to https://community.nodebb.org and am unable to log in afterwards.

**Comment by henrikekblad** [comment] 2017-02-09 20:11
Could it be related to websocket vs http? Does the two variants go through the same routes/checks? 
(I'd imagine a spam bot would use http-requests when possible)

**Comment by julianlam** [comment] 2017-02-09 20:12
The IP blacklist system only stops people from registering or logging in, and those two requests are done over http, not websockets.

**Comment by henrikekblad** [comment] 2017-02-09 20:21
Ok, then I'm clueless. I've deleted the user, added ip to blacklist.  They have still successfully registered 4 new accounts and posting their darn useless (no-follow) links.

**Comment by julianlam** [comment] 2017-02-09 20:24
In that case, I would recommend you just ban their IP from the system level. If you're on Ubuntu, just run `ufw deny from {their IP}`

**Comment by henrikekblad** [comment] 2017-02-09 20:25
Yes, the thought has crossed my mind. But messier to administrate ;)

**Comment by henrikekblad** [comment] 2017-02-09 20:30
BTW.. on the subject.. This is a new one I've seen recently (targeting electronics forums)
https://forum.mysensors.org/topic/6090/is-there-an-easier-way-to-compare-the-voltages-of-these-two-sensors

**Comment by exomarty** [comment] 2017-02-09 20:30
Tested myseld again and worked, not sure which  was the problem before
I think the problem is anyone can just log on their mobile to login then go back to his banned original ip and keep using the forum to spam or post shit

**Comment by psychobunny** [comment] 2017-02-09 20:32
that makes sense actually. IP ban might want to reverse look for users that have had that IP range and log them out

**Comment by henrikekblad** [comment] 2017-02-09 20:34
Doesn't removal of a user also remove/revoke their session?

**Comment by psychobunny** [comment] 2017-02-09 20:38
Delete, yes - IP ban, not currently AFAIK

**Comment by henrikekblad** [comment] 2017-02-09 20:44
Do I need to restart/reload after applying bans? Because I haven't...

**Comment by exomarty** [comment] 2017-02-09 23:51
Not needed @henrikekblad

**Comment by henrikekblad** [comment] 2017-02-10 08:20
Ok, we tried adding (our own) test ip and ban seems to work. You can close this.

Would still be interesting to know how the spammer found a way of circumvent things and still get the blocked ip logged.

**Closed** 2017-03-09 21:32 UTC
Labels: bug
