### ISSUE TITLE
PWA Not Working

### ISSUE THREAD

**Issue by sm2x** [NodeBB/NodeBB#9200] opened 2021-01-15 21:53 UTC
Ubuntu 18.04
NodeBB 1.16.1
Redis 4.0.9
Nginx 1.14.0

I am having "Manifest: Line: 1, column: 1, Syntax" error
![image](https://user-images.githubusercontent.com/6595333/104781858-39335400-57be-11eb-9ae1-9d247f8b57c0.png)

And here is the "manifest.webmanifest" content:

{"name":"OUR HUB","short_name":"The hub of innovation and excellence.","start_url":"https://xxx.yyyyyy.zzz","display":"standalone","orientation":"portrait","theme_color":"#ffffff","background_color":"#ffffff","icons":[{"src":"/assets/uploads/system/touchicon-36.png","sizes":"36x36","type":"image/png","density":0.75},{"src":"/assets/uploads/system/touchicon-48.png","sizes":"48x48","type":"image/png","density":1},{"src":"/assets/uploads/system/touchicon-72.png","sizes":"72x72","type":"image/png","density":1.5},{"src":"/assets/uploads/system/touchicon-96.png","sizes":"96x96","type":"image/png","density":2},{"src":"/assets/uploads/system/touchicon-144.png","sizes":"144x144","type":"image/png","density":3},{"src":"/assets/uploads/system/touchicon-192.png","sizes":"192x192","type":"image/png","density":4},{"src":"/assets/uploads/system/touchicon-512.png","sizes":"512x512","type":"image/png","density":10},{"src":"/assets/uploads/system/maskableicon-orig.png","type":"image/png","purpose":"maskable"}]}

**Comment by julianlam** [comment] 2021-01-15 21:53
Duplicate of #9193

**Comment by julianlam** [comment] 2021-01-15 21:54
It might not look it, but the resolution to #9193 should resolve this as well. :)

**Comment by sm2x** [comment] 2021-01-15 21:58
thanks Julian

**Comment by psychobunny** [comment] 2021-01-16 02:22
@sm2x hi can I get a link to your forum, just reopening temporarily as this may potentially be a separate issue. If it's private, DM psychobunny at our forums at https://community.nodebb.org ?

Thanks!

**Comment by julianlam** [comment] 2021-02-05 16:14
@sm2x Is this issue still happening?

**Comment by garyry** [comment] 2021-04-03 17:50
> @sm2x Is this issue still happening?

Im using my installation as PWA without any problem. (v1.16.2)

**Closed** 2021-09-27 20:11 UTC
