### ISSUE TITLE
User Digest settings are being ignored

### ISSUE THREAD

**Issue by phit** [NodeBB/NodeBB#6126] opened 2017-11-27 17:52 UTC
- **NodeBB version:** 1.6.x
- **NodeBB git hash:** 95f7b7b8e828e7203af6e6b815358ae973c0dff6

- **Database type:** mongo

- **Exact steps to cause this issue:**
multiple users reported to me that they are getting digest emails since my update to 1.6.x, even though they have their digest settings to off

   forum is set to weekly digest by default in the ACP, looks like that setting is used instead of the settings set by the user?

- **What you expected:**
not getting mails

- **What happened instead:**
they get mails

I wonder if this was introduced with the fix in https://github.com/NodeBB/NodeBB/issues/5770 and NodeBB somehow thinks those users had never saved their settings even though they did just a long time ago

**Comment by julianlam** [comment] 2017-11-28 16:49
@phit Unfortunately I haven't been able to reproduce (at least, via our testing suite).

I added a couple new tests to test this specifically, and they all passed: https://github.com/NodeBB/NodeBB/pull/6130

**Comment by phit** [comment] 2017-11-28 18:26
Yeah I did for multiple people, before reporting this. They all named the first sunday after I updated the forums as the date this started.

**Comment by julianlam** [comment] 2017-11-28 18:27
In that case it could very well be that the changes @baris made fixes this. Can you try upgrading to v1.7.0?

**Comment by phit** [comment] 2017-11-28 18:32
Yeah, it's on my to-do just haven't found time to locally test the upgrade.

**Comment by julianlam** [comment] 2017-11-30 17:30
Great, please do let us know when you have a chance 😄 I will pre-emptively close this for now.

**Closed by julianlam** 2017-11-30 17:30 UTC
Labels: bug, needs confirmation, regression

**Comment by henrikekblad** [comment] 2017-12-10 21:11
Hi, 

Something is definitely behaving differently since we upgraded to 1.7.2 a few days ago. 

Looks like we're sending out digest emails to all our members. This has raised (angry) reactions from members that previously opted out for these emails.

<img width="1112" alt="screen shot 2017-12-10 at 22 01 45" src="https://user-images.githubusercontent.com/5717075/33809352-d274d166-ddf5-11e7-836a-9432ab965211.png">

Anything we can do short-term to solve this until it has been fixed? (Like temporary disabling digests for all users?)

**Comment by barisusakli** [comment] 2017-12-10 21:21
Can you go to /admin/settings/user#default-user-settings and check if digest is set to `off`?

**Comment by henrikekblad** [comment] 2017-12-10 21:30
It's set to weekly. 

<img width="1205" alt="screen shot 2017-12-10 at 22 27 06" src="https://user-images.githubusercontent.com/5717075/33809563-4c116ce8-ddf9-11e7-90f9-5a9590d59a6e.png">

Hmm... wonder why it didn't send to (almost) all users in the earlier version?

**Comment by barisusakli** [comment] 2017-12-10 21:32
Could be due to a bug that was fixed. If you set that to off your issue should be fixed.

**Comment by mfalkvidd** [comment] 2017-12-11 07:57
Will setting it to off affect users who have actively selected to receive weekly digests?

**Comment by phit** [comment] 2017-12-11 08:05
from my experience, no, users that have explicitly selected something are not affected by the default value

**Comment by barisusakli** [comment] 2017-12-11 13:52
That's correct the default only affects users who haven't explicitly set their settings.
