### ISSUE TITLE
Autocomplete multi-word usernames

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11400] opened 2023-03-26 12:23 UTC
### NodeBB version

Last (I checked at https://community.nodebb.org)

### What you expected

When tagging a user, as soon as you type @ an auto-complete window opens that advances as you type.
But in multi-word usernames (for example James Anderson), you have to use a hyphen between the words (`@james-anderson`), and there as soon as I type the hyphen, I don't have autocomplete to continue.
A screenshot is attached

https://user-images.githubusercontent.com/78599753/227775092-ec7fd2c2-354d-4e20-89a8-466277e3fb13.mp4

### What happened instead

The completion will continue to appear even after typing the dash, and will display the appropriate usernames (for example "`@james-a`" will autocomplete "james anderson")

**Comment by julianlam** [comment] 2023-03-26 13:29
Unfortunately this is a limitation with NodeBB as we allow for searching by username but not by user slug (which is what Mentions does.

As a workaround you can type the full name of the user with a dash in place of the space, it will still resolve into a mention despite not showing up in the autocomplete

**Comment by julianlam** [comment] 2023-03-26 13:29
We can of course look into fixing the underlying limitation, but it is not n easy bug fix.

**Comment by ShlomoCode** [comment] 2023-03-26 13:33
Perhaps it is possible to artificially search using a username with spaces, even though a hyphen was typed

**Comment by julianlam** [comment] 2023-03-26 13:35
While that would solve the issue with spaces, that is not an adequate solution because a user slug collapses more than just space characters into dashes.

**Comment by ShlomoCode** [comment] 2023-03-26 16:54
@julianlam I discovered another problem,
When I tag a user of one word (for example @james), and together with him also a user of 2 words - the first of which is the same as the first user (@james-anderson), the user of the 2 words will not be mentioned even though I wrote his full name manually including a hyphen!
When I only tag the user with the 2 words, it works fine.
Here is a picture:
<img width="1407" alt="CleanShot 2023-03-26 at 19 50 49@2x" src="https://user-images.githubusercontent.com/78599753/227791420-1e5b1c21-99e5-45b6-928e-369888da92d6.png">

**Comment by ShlomoCode** [comment] 2023-04-06 17:04
@julianlam Thank you!
Is https://community.nodebb.org updated to version v3.0.0-rc.2 that was released yesterday (and contains version 4.0.6 of nodebb-plugin-mentions)?
Because I don't see there that the problem has been fixed

**Comment by ShlomoCode** [comment] 2023-08-17 13:40
@julianlam still not working (nodebb 3.3.0)

**Comment by julianlam** [comment] 2023-08-17 13:58
What are the slugs you are using? The test cases should catch it.

**Comment by ShlomoCode** [comment] 2023-08-17 14:14
@julianlam fot example `[@james-fox](https://community.nodebb.org/uid/24134)`

Here is a recent screenshot:
https://github.com/NodeBB/NodeBB/assets/78599753/f226b224-744a-4c98-9b4f-b793424bd2d7

**Comment by ShlomoCode** [comment] 2023-09-11 00:30
@julianlam Can you reopen this issue?
As mentioned, the problem has not been solved
Or should I open a new issue for this?

**Comment by JorensM** [comment] 2023-10-05 17:05
@julianlam may I work on this?

**Comment by julianlam** [comment] 2023-12-01 18:38
@ShlomoCode I am not able to reproduce this on my own development instance:

![image](https://github.com/NodeBB/NodeBB/assets/923011/8ca939d2-83f9-4b1f-af15-281342d39190)

**Comment by julianlam** [comment] 2023-12-01 18:47
> @julianlam Can you reopen this issue?
> As mentioned, the problem has not been solved

That's correct, I opted not to solve it as explained above:

> Unfortunately this is a limitation with NodeBB as we allow for searching by username but not by user slug (which is what Mentions does).

The linked commit resolving the issue pertained to the second issue, where mentioning a user would cause an incorrect mention if another user with a shorter subset of that name were also mentioned.

**Closed by julianlam** 2023-12-01 18:47 UTC
Labels: bug
