### ISSUE TITLE
Notifications not grouping properly

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3972] opened 2015-12-19 20:56 UTC
Notifications dropdown has different count and /notifications route shows a different count and both are wrong.

<img width="1119" alt="screen shot 2015-12-19 at 12 52 41 pm" src="https://cloud.githubusercontent.com/assets/10014774/11915176/97581a78-a64f-11e5-9f6a-ec78e6c33e25.png">

<img width="621" alt="screen shot 2015-12-19 at 12 55 14 pm" src="https://cloud.githubusercontent.com/assets/10014774/11915180/cd1b82da-a64f-11e5-9470-d0a91f97f3cb.png">

**Comment by julianlam** [comment] 2015-12-19 21:56
Duplicate of #3965

**Comment by julianlam** [comment] 2015-12-19 21:56
In fact, I even tagged you in the other issue :laughing:

**Closed by julianlam** 2015-12-19 21:56 UTC

**Comment by pichalite** [comment] 2015-12-20 00:40
Oops
