### ISSUE TITLE
Browser title bug

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#2854] opened 2015-03-12 04:08 UTC
There´s some bugs on browser title update.
1- On safari on mac, if you enter home or categories will go just fine, but if you enter on a topic the browser title goes back to default after a second. ( default = first browser title that was loaded on that window)
This happens on https://community.nodebb.org, please check it out
On my local at 0.6 runs good, but tested it on 0.7 and seems broken

2- Another self bug. I have my own theme and browser title won't update after first page load, no mather how many pages you navigate, it will stays static. Only on home goes back to default.
Theme is actually same as vanille with minor changes.
header.tpl is same

```

	<title>{browserTitle}</title>
	<!-- BEGIN metaTags -->
	{function.buildMetaTag}
	<!-- END metaTags -->
```

this problem exists on 0.6 and 0,7

**Comment by barisusakli** [comment] 2015-03-12 20:24
Does this only happen on safari?

**Comment by martyalicante** [comment] 2015-03-12 20:45
The firsr point. Yes. Seems only safari. 
About my theme or other themes but defaults like vanilla, seems to happen in all browsers

**Comment by barisusakli** [comment] 2015-04-16 18:38
Looks like safari doesnt let you change browser title with document.title. 

There are some suggestions here http://stackoverflow.com/questions/17640862/javascript-document-title-doesnt-work-in-safari but they look like overkill to me.

**Comment by julianlam** [comment] 2015-04-16 18:40
Then I would classify this as `wontfix`, as it's something we cannot reliable work around...

**Comment by barisusakli** [comment] 2015-04-16 18:41
One solution is to disable ajaxify on safari :trollface:

**Comment by psychobunny** [comment] 2015-04-16 18:42
> Then I would classify this as `wontfix`, as it's something we cannot reliable work around...

Hmm I dunno, I'm sure there's a way, supporting safari seems like something we shouldn't just abandon


aaaand julian reassigns to psychobunny

**Comment by julianlam** [comment] 2015-04-16 18:47
> aaaand julian reassigns to psychobunny

Saying it sarcastically doesn't stop it from happening :trollface:  *assigned to @psychobunny *

**Comment by psychobunny** [comment] 2015-04-16 18:47
Also this: 

> On my local at 0.6 runs good, but tested it on 0.7 and seems broken

so clearly it was working before, just have to track down what changed I guess

**Comment by psychobunny** [comment] 2015-04-16 18:55
I can't reproduce this on our community using Safari 5.1.7 for Windows (latest version)

Probably a bug on the latest Safari for Mac, @martyalicante can you give me the version please (and then I'll try and get my hands on a Mac... :P)

**Comment by martyalicante** [comment] 2015-04-16 19:57
Safari on windows passed away time ago
Last version on the mac is 8.0.5 on OSX yosemite 10.10.3
You can test it also on iphone ipad last version 8.3

**Comment by julianlam** [comment] 2015-07-18 22:32
Is this bug present on the latest version of Safari?

**Comment by martyalicante** [comment] 2015-07-18 23:05
Yes

**Comment by martyalicante** [comment] 2016-02-09 02:41
this is already solved so i bet you can stop delaying it lol :+1:

**Closed** 2016-02-09 02:43 UTC
Labels: bug
