### ISSUE TITLE
Where is package.json on 1.7.x branch?

### ISSUE THREAD

**Issue by mchenx** [NodeBB/NodeBB#6221] opened 2018-01-10 15:42 UTC
when I tried to install nodebb by executing 
`node app.js --setup`
I encountered an error saying 'nconf' module not found, so I tried on install dependencies by running
`npm i`
and then I encountered another error saying package.json not found

Am I missing something here?

**Comment by julianlam** [comment] 2018-01-10 16:07
You should be able to kickstart setup by running `./nodebb setup`. Apologies on the confusing instructions, where did you read that you had to run `node app --setup`?

**Comment by pitaj** [comment] 2018-01-10 16:08
Use `./nodebb setup`. It will automatically handle the package.json copying and updating. You can pass a json object just like `node app --setup`.

The default package.json is in the install directory.

What tutorial or documentation are you using which says to use `node app`?

**Comment by mchenx** [comment] 2018-01-11 01:15
Thanks guys!

I actually visited [https://docs.nodebb.org/](url) by clicking the  "Documentation & Installation Instructions" in the readme.MD, however I did find any instructions but some contribution guidance for translation, so I went to the old document which led me to "https://nodebb.readthedocs.io/en/latest/installing/os/windows8.html", and that was for 1.5.x but I thought the installation probably the same way, didn't realized it changed.

I'm currently trying to install nodebb on windows 10 (as I left my macbook my home), tried 
`nodebb setup`
thrown exception saying 
`net.js:701
throw new TypeError(no`

**Comment by pitaj** [comment] 2018-01-11 03:32
Seems like the error message got cut off there. Do you have the rest?

**Comment by mchenx** [comment] 2018-01-11 03:59
here is the stack trace

![image](https://user-images.githubusercontent.com/1550186/34808015-eadfb0c4-f6c6-11e7-8e77-cf760a15a41c.png)

**Comment by pitaj** [comment] 2018-01-11 21:45
What git hash are you on? `git rev-parse HEAD`

**Comment by mchenx** [comment] 2018-01-12 02:53
dabb1e8d6dbeb143976a9ad76d0233daae450467

**Comment by pitaj** [comment] 2018-01-12 03:08
Are you using the 1.7.x or the master branch? If master, try pulling latest please.

**Comment by pitaj** [comment] 2018-01-12 03:19
This is caused by a regression introduced that hasn't been backport-fixed in the v1.7.x branch.

It was fixed in 4387d5d466d34fce2ea07260a70fd0cd361be9cc and introduced in 748067e8c8742319ee61f785ddc325b88418e637. To fix it, you can run `git checkout v1.7.3` (a tag before the regression) or you can use the master branch.

**Comment by mchenx** [comment] 2018-01-12 06:58
Thanks!  I'm not have nodebb setup locally.

I actually got a npm error during the setup


But I simply run "npm i" manually and then "nodebb", and eventually I got nodebb humming!  looks nice~

**Comment by pitaj** [comment] 2018-01-14 18:34
Closed in favor of #6237

**Closed by pitaj** 2018-01-14 18:34 UTC
Labels: question
