### ISSUE TITLE
email only login broken

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#10027] opened 2021-11-23 03:13 UTC
1. create forum
2. login as admin
3. go to acp and change login  type to email only
4. logout
5. cant login anymore as admin

https://github.com/NodeBB/NodeBB/commit/e726048e0c6c37983401afccfbf923b9a6a33185#diff-4e36c698c095e4963071129dfe5e708e490e89deddfce8ebfebdba0ff5fbff36

Happens because the uid of the user is not added to `email:uid` on account creation.

**Comment by julianlam** [comment] 2021-11-23 19:00
Thanks @barisusakli -- this is an interesting regression brought on by the breaking change to overhaul how emails are treated in the system. A newly registered user's email is now no longer automatically assigned to the account, but only done once the email itself is verified.

This does pose an issue, as you've pointed out, if login via "email only" is enabled, since it means standard username login is no longer allowed and any account that have not verified their email are now no longer able to log in.

**However**, one can argue that this is actually working by design, as an email entered on registration but not confirmed is meaningless. One shouldn't do any sort of action with an unverified email, including sending digest emails, and yes... logging in via email as the identifier.

Any workaround I can think of has drawbacks:

* Allow username login only if email not verified
    * Relies on having to save a separate set of unverified emails purely for login services :-1:
* Autoconfirm emails if an emailer is not installed
    * Wouldn't work well with fallback emailer, plus confirming emails that aren't really confirmed defeats the purpose of confirming emails in the first place

The only real solution I can think of is to not allow email only login. The only options going forward should just be:

![image](https://user-images.githubusercontent.com/923011/143087226-49b44206-63b4-4be9-b37b-83646eb407f9.png)

**Comment by julianlam** [comment] 2021-11-23 19:03
While I am more than happy to cut features :scissors: ... I pause only because I want to know why we have email only login at all.

* If there was a specific use case it was meant to address, then that would be helpful to know
* If it was added purely to have options for the sake of options... _snip snip_ :scissors:

**Comment by barisusakli** [comment] 2021-11-23 19:27
I have no objections to removing `email only`, needs an upgrade script to change the value to `username-email` if it's set to `email`. 

Email only/username only was added long ago for this https://github.com/NodeBB/NodeBB/issues/2618,

**Comment by julianlam** [comment] 2021-11-23 19:47
Okay, that's an acceptable tradeoff. The increased attack surface is so minimal as to be negligible.

**Closed** 2021-11-23 19:46 UTC
Labels: bug, regression
