### ISSUE TITLE
Login not updated

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#3515] opened 2015-08-28 15:16 UTC
I couldn't find a better title.
I just updated from 6e714a5 to a1fb234

When I log in, I have the right access, even ACP, but the site header is still showing "Register"/"Connect"

This involve that I can't see the unread navigation, reserved to logged users.

At the update, the Site Title disappeared too.

I cleared cache and reset all plugins but it remains the same.
I tried in dev mode.
The only thing new is
```
28/8 17:07 [12930] - warn: [meta/templates] Partial not loaded: partials/variables/category.tpl
28/8 17:07 [12930] - warn: [meta/templates] Partial not loaded: partials/variables/reset_code.tpl
28/8 17:07 [12930] - warn: [meta/templates] Partial not loaded: partials/variables/tag.tpl
```
and so on.

Thanks for any input

**Comment by julianlam** [comment] 2015-08-28 15:27
Looks like a duplicate of #3513? If so, please close this issue and track there @tedr56 :smile:

**Comment by julianlam** [comment] 2015-08-28 15:36
Nevermind, #3513 got closed, but this is still an issue on `master`, according to at least 3 reports now.

**Comment by tedr56** [comment] 2015-08-28 15:39
Indeed, the trick to switch to v0.8.x branch resolv the issue.
But still happening on master.

**Comment by julianlam** [comment] 2015-08-28 15:40
Thanks for confirming @tedr56 :smile: 

... and also thanks for sticking with us for so long! Early adopter, right there :point_up:

**Comment by tedr56** [comment] 2015-08-28 15:42
You're welcome.
I stick along the good work ;)

**Comment by julianlam** [comment] 2015-08-28 16:19
48512bff6b90a89418adddfa93e265dffb3630cf is the first bad commit
commit 48512bff6b90a89418adddfa93e265dffb3630cf
Author: barisusakli <barisusakli@gmail.com>
Date:   Thu Aug 27 19:22:51 2015 -0400

    get rid of app.exposeConfigToTemplates

**Comment by julianlam** [comment] 2015-08-28 16:35
1af39bb44e797a3039cd87205db559056840a27c

**Comment by julianlam** [comment] 2015-08-28 17:00
Fixed on latest themes :smile:

**Closed by julianlam** 2015-08-28 17:00 UTC
