### ISSUE TITLE
Bug with reloading page

### ISSUE THREAD

**Issue by dimk00z** [NodeBB/NodeBB#3057] opened 2015-04-19 10:47 UTC
After upgrade "new topic" stop working.
 But "new topic" is working after reloading the page.
Same thing with the correct theme display of forum topics.

https://community.nodebb.org/topic/4212/cannot-create-new-topic/21

**Comment by julianlam** [comment] 2015-04-19 16:02
Seems to be related to outdated dependent packages. Closing as it is a configuration issue and not a bug.

**Closed by julianlam** 2015-04-19 16:02 UTC
