### ISSUE TITLE
Cannot set property 'user' of undefined on login page

### ISSUE THREAD

**Issue by maissani** [NodeBB/NodeBB#3489] opened 2015-08-25 09:06 UTC
After upgrade when someone try to login into nodebb. 
If the user and password match node bb will display : 
Cannot set property 'user' of undefined
Tried it with a couple of themes including the default one. 
This break the login feature. 

Cordialy, 
Mehdi Aissani

**Comment by maissani** [comment] 2015-08-25 09:37
This may en issue with passport 0.2.1 to 0.3.0 upgrade. 
Some lines of code may have to be updated because of passport changes. 

Best Regards

**Comment by maissani** [comment] 2015-08-25 10:23
Please look at this: 
If this is not relevant to this issue please ignore: 
https://github.com/jaredhanson/passport/commit/66fb128712987a44ef105fd35be3da43546772f1#diff-04c6e90faac2675aa89e2176d2eec7d8

Cordially

**Comment by julianlam** [comment] 2015-08-25 11:36
Mehdi, please show us the entire stack trace, as the error itself does not tell us where the problem originates.

**Comment by julianlam** [comment] 2015-08-25 11:36
Also report your commit hash (`git rev-parse HEAD`) so we can attempt to reproduce.

**Comment by maissani** [comment] 2015-08-25 11:57
Commit Hash : 7210ffdde9f837c8eff9a3b76ef1eb653365362f
Wait a minute there is no trace in logs, i ll try to obtain the trace of the error displayed in the error flash message.
I ll update this issue quickly. Need 20 min max.

best regards

**Comment by maissani** [comment] 2015-08-25 12:12
There is no errors in log file. 
This show an error for the user but no error are output in logs , including launching nodebb via node app dev that generaly output most of errors.

**Comment by maissani** [comment] 2015-08-25 13:10
Fixed strangely by thoses lines of code: 

// remove all node_modules
rm -rf node_modules/
// re-install dependencies
npm install
// install redis and redis-server (There is no needs to execute i think, but i have done it ) 
npm install redis
npm install connect-redis

Lines of code:
Found @ https://community.nodebb.org/topic/6298/nodebb-v0-7-3/19

Related about nodebb upgrade command that sometimes doesn't do the job correctly after pulling and launching upgrade commande.

You can close this issue, i think.

**Comment by julianlam** [comment] 2015-08-25 13:11
good good, thanks for confirming that it is resolved!

**Comment by maissani** [comment] 2015-08-25 13:40
Thanks @julianlam

**Comment by frissdiegurke** [comment] 2015-08-26 10:53
@julianlam I'm currently encountering this problem on the NodeBB community. Cannot login thought.
The POST to /login returns 403 with content "Cannot set property 'user' of undefined"

**Comment by frissdiegurke** [comment] 2015-08-26 11:24
Due to the impact of this (and the assumption that 403 response-code prevents it from being noticed by you guys yet) I'll additionally ping @barisusakli and @psychobunny :wink:

**Comment by maissani** [comment] 2015-08-26 14:03
@frissdiegurke Have you try to execute the lines of codes previously pasted in this issue that fix this bug to my environement. 

Try this @the root of your nodebb ( where the folder node_modules is): 
// remove all node_modules
rm -rf node_modules/
// re-install dependencies
npm install
// install redis and redis-server (There is no needs to execute i think, but i have done it )
npm install redis
npm install connect-redis

Best Regards, 
Mehdi Aissani

Ps: if you can't fix this issue with it please paste your commit hash and stack trace of your error. 
If you can't get logs about it like me, please try to start the app with : ./node app dev

@julianlam If @frissdiegurke fix it with those commands, can you add to the wiki the solve that i have providen as a known issue that could be fixed by clearing and re-install node modules.

**Comment by frissdiegurke** [comment] 2015-08-26 14:41
@maissani A bit of misunderstanding here: I'm trying to login into https://community.nodebb.org and that fails.

So it's up to @julianlam @barisusakli or @psychobunny to fix their dependencies.
And since it's in their interest to get it running ASAP I've pinged them all.

**Comment by julianlam** [comment] 2015-08-26 14:50
@frissdiegurke It's odd as I cannot reproduce this on the community forum. Logged out and logged back in with no issues.

**Comment by frissdiegurke** [comment] 2015-08-26 15:06
weird. I just tried with another browser and my second account, but both failed with the issue.
A password-reset didn't work either.
I'll just send you my second account's data to test out.

**Comment by julianlam** [comment] 2015-08-26 15:07
@frissdiegurke No need, reproduced in incognito, oddly.

**Comment by julianlam** [comment] 2015-08-26 15:15
jaredhanson/passport#400

**Comment by julianlam** [comment] 2015-08-26 15:18
In the meantime, I overrode the forum's `package.json` to use `passport` `^0.2.2`, ran `npm i`, and login works again.

A workaround until we can properly resolve the issue.

**Comment by julianlam** [comment] 2015-08-27 12:45
This blocks the next version of NodeBB from launching.

**Comment by julianlam** [comment] 2015-08-27 14:41
This is no longer blocking NodeBB launch. Installs with the 2factor plugin will run into issues as it depends on an old version of passport, so that's waiting on jaredhanson/passport-totp#5 to be merged.

**Comment by julianlam** [comment] 2015-08-27 19:50
Fixed in julianlam/nodebb-plugin-2factor@ed5b02f2176ad72fccc3e15e5152d6fe0eab13fb

**Closed by julianlam** 2015-08-27 19:50 UTC
Labels: bug, low priority, waiting for upstream

**Comment by olivierlambert** [comment] 2015-10-13 11:12
Same issue for me, the (sadly usual with npm, ie removing node_modules) procedure did the trick.

We are also developing [a node app](https://github.com/vatesfr/xo-web), and encountering the same general problems with npm. Happy to see we are not alone ;) Keep up the good work on NodeBB!
