### ISSUE TITLE
Multiple badges aren't shown

### ISSUE THREAD

**Issue by thewilloftheshadow** [NodeBB/NodeBB#9496] opened 2021-04-19 17:59 UTC
- **NodeBB version:** v1.17.0-beta.5
- **NodeBB git hash:** c484ed4858b9451e015da1deb269191020d862eb
- **NodeJS version:** v14.15.3

- **Installed NodeBB Plugins:** Unrelated, but if you want them ask (there's a lot). Using persona theme

- **Database type:** mongo
- **Database version:** Latest on atlas

- **Exact steps to cause this issue:**
- Enable Multiple Badges in the ACP
- Update to beta.5

- **What you expected:**
- Multiple badges are shown by the user's name when they select multiple badges

- **What happened instead:**
- Only one badge is shown, and after returning to the edit profile page, all the other badges are unselected
- It is random which one remains as far as I can tell

https://user-images.githubusercontent.com/35580099/115281878-1db64d00-a10f-11eb-86f5-11551b5606b4.mp4

**Comment by barisusakli** [comment] 2021-04-19 18:02
Seems to be working fine at https://community.nodebb.org/topic/15449/links-in-digest-emails-are-broken/9

**Comment by barisusakli** [comment] 2021-05-17 16:56
Make sure flatpickr dependency isnt used. It seems to be overriding $.serializeObject and breaking this page.

**Comment by barisusakli** [comment] 2021-05-17 17:19
@thewilloftheshadow do you have nodebb-plugin-poll installed by any chance?

**Comment by thewilloftheshadow** [comment] 2021-05-17 17:21
@barisusakli indeed I do

**Comment by barisusakli** [comment] 2021-05-17 17:25
Can you try disabling it and rebuild & restart. See if that fixes the issue.  https://github.com/NodeBB/nodebb-plugin-poll/issues/125

**Comment by thewilloftheshadow** [comment] 2021-05-17 18:00
@barisusakli yep that fixed the issue

**Comment by barisusakli** [comment] 2021-05-17 21:21
I will close this since it needs to be fixed in the poll plugin. The issue is the poll plugin is including a different version of jquery serialize object which breaks the profile edit page.

**Closed by barisusakli** 2021-05-17 21:21 UTC
