### ISSUE TITLE
WSS websockets handshake error

### ISSUE THREAD

**Issue by fais3000** [NodeBB/NodeBB#8491] opened 2020-07-11 08:53 UTC
- **NodeBB version**: 1.14.1
- **Database type:** mongo and redis for clustering
- **Database version:** 
-- Mongo db version v3.6.9
-- Redis server v=3.0.6
- Behind Nginx: nginx version: nginx/1.10.3 (Ubuntu)
- Behind Cloudflare (Performance Disabled)
- **Installed NodeBB Plugins:** 
Active plugins:
	* nodebb-plugin-audio-control (installed, disabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-composer-redactor (installed, disabled)
	* nodebb-plugin-custom-pages (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-dictionary (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-emoji-extended (installed, enabled)
	* nodebb-plugin-emoji-one (installed, enabled)
	* nodebb-plugin-imgur (installed, enabled)
	* nodebb-plugin-jwt (installed, enabled)
	* nodebb-plugin-jwt-oauth2 (installed, disabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-ns-embed (installed, disabled)
	* nodebb-plugin-postmentions (installed, enabled)
	* nodebb-plugin-recent-cards (installed, enabled)
	* nodebb-plugin-shoutbox-neho (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-plugin-sso-facebook (installed, enabled)
	* nodebb-plugin-sso-google (installed, enabled)
	* nodebb-plugin-write-api (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

**Problem**
When forum is setup in Clustering Mode https://docs.nodebb.org/configuring/scaling/ The websockets throw random 400 errors. e.g You'll see following error thrown if you stay on any page of https://definedictionarymeaning.com for a while.
```
socket.io.js:8 WebSocket connection to 'wss://definedictionarymeaning.com/socket.io/?EIO=3&transport=websocket&sid=Ayk4SxShbJNR5b7SAAAZ' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Config.json**
```
{
    "url": "xxxx",
    "secret": "xxxx",
    "database": "mongo",
    "port": [
        "4567",
        "4569",
        "4570"
    ],
    "mongo": {
        "host": "localhost",
        "port": "27017",
        "username": "",
        "password": "",
        "database": "",
        "uri": ""
    },
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "database": 0
    }
}
```

**Nginx**

```
upstream io_nodes {
    ip_hash;
    server 127.0.0.1:4567;
    server 127.0.0.1:4569;
    server 127.0.0.1:4570;
}

server {
    listen 443 ssl;

    ssl on;
    ssl_certificate         path;
    ssl_certificate_key     path;

    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

    server_name server;

 	# Bad Bot Blocker
	include /etc/nginx/bots.d/ddos.conf;
 	include /etc/nginx/bots.d/blockbots.conf;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_redirect off;

    # Socket.io Support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";


    gzip            on;
    gzip_min_length 1000;
    gzip_proxied    off;
    gzip_types      text/plain application/xml text/javascript application/javascript application/x-javascript text/css application/json;


    location @nodebb {
        proxy_pass http://io_nodes;
    }

    location ~ ^/assets/(.*) {
        root /var/www/nodebb/;
        try_files /build/public/$1 /public/$1 @nodebb;
    }

    location /plugins/ {
        root /var/www/nodebb/build/public/;
        try_files $uri @nodebb;
    }

    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://io_nodes;
    }

    location /ads.json {
        root /var/www/nodebb/public/;
    }
    location /ads.txt {
        root /var/www/nodebb/public/;
    }
}
```

**Comment by pitaj** [comment] 2020-07-11 14:16
Does this happen if you run it with only two entries in the IP hash?

**Comment by fais3000** [comment] 2020-07-11 18:11
@pitaj Yes, just changed above to 2 ports and 2 IP hash entries in Nginx. Still same error.

**Comment by fais3000** [comment] 2020-07-14 08:39
@barisusakli @pitaj Guys, this is causing a really sub par experience for the users and chat become too slow (some pooling requests fail some succeed). Kind of defeating the purpose of scaling if the performance is degraded compared to running nodebb on one port. Any suggestions?

How many ports are used to run https://community.nodebb.org. Do you reckon cloudflare could be causing this?

**Comment by julianlam** [comment] 2020-07-14 12:01
We run community.nodebb.org on two ports, without issue. You can try disabling CF acceleration to see if that resolves the issue. IIRC we are not using CF acceleration on our site.

**Comment by fais3000** [comment] 2020-07-14 15:08
@julianlam I saw this comment before, what is CF acceleration? We are on Cloudflare enterprise plan but can't find this option. Additionally in page rules we have following settings.

![image](https://user-images.githubusercontent.com/25720059/87442255-8109d080-c60d-11ea-9830-81f073278191.png)

**Comment by julianlam** [comment] 2020-07-14 15:43
Basically, it means to only use CF for DNS routing. It is an effective way to sort out whether CF is the problem or not. If you switch from orange cloud to grey cloud (in the DNS page), and the issue persists, then it is indicative that the problem is not CF.

**Comment by fais3000** [comment] 2020-07-14 15:46
@pitaj @barisusakli @julianlam So I've solved it. At the end it has nothing to do with cloudflare. The culprit is Nginx vhost configurations from the docs https://docs.nodebb.org/configuring/scaling/.  Following upgrade headers are needed are needed to resolve the handshake errors in both blocks.

```
    location @nodebb {
        proxy_pass http://io_nodes;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://io_nodes;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
```

I've further tested these settings with 2 to 9 ports. They all seem to work properly now without the 400 handshake error.

**Comment by julianlam** [comment] 2020-07-14 15:47
Wonderful, thank you for closing the loop and letting us know the problem! I will be sure to check for this next time someone raises this as an issue :smile:

**Closed** 2020-07-14 15:47 UTC
