### ISSUE TITLE
Search algorithm limited

### ISSUE THREAD

**Issue by jbob182** [NodeBB/NodeBB#3316] opened 2015-07-13 02:28 UTC
NodeBB has been serving us at the FOG project fairly well, however the single largest complaint we receive from our user base, and even our own development team, is the search capabilities or lack there of. A robust search algorithm is crucial for a forums that is used for debugging issues people have with their FOG servers. The current search setup only works if you know the exact terms to search, and even then a word-for-word search of the title won't even populate the correct topics. Often times generic and ambiguous search terms will need to be used to find anything semi-relevant.

See https://forums.fogproject.org/topic/4962/ambiguous-search-terms for an example. 

While this may not technically qualify as a "bug" I would say its a lacking area that needs attention.

**Comment by julianlam** [comment] 2015-07-13 02:30
Hi Joe,

Which search engine plugin are you using?

**Comment by jbob182** [comment] 2015-07-13 02:33
We are using nodebb-plugin-dbsearch , is there another we should look into?

**Comment by julianlam** [comment] 2015-07-13 02:37
If you have Solr installed, give that one a try. You'll have to install
solr on the machine itself, and reindex your forum data from the plugin's
settings page.

**Comment by wayneworkman** [comment] 2015-07-13 12:48
I agree with this bug/feature request. I strongly dislike how the current NodeBB search feature is performing. I find it difficult to find anything relevant and it only matches words, and pieces of words... nothing relevant ever shows up unless you accidentally get an exact match. And even with exact matches, I often have to specify who made the post/thread and if it was in the title or content. It's aggravating. 

Half of the reason for having a forum is for people to read the forum... so that they don't post duplicate questions. However if they cannot easily search past topics, they will have to ask a person with a new thread... when they might have solved the issue on their own if the search feature worked better.

**Comment by julianlam** [comment] 2015-07-14 02:42
It's definitely good feedback, thanks @wayneworkman. @barisusakli maintains the dbsearch plugin, so I'm sure he'll want to make some changes based on this.

@jbob182 @FokkeZB Any luck with Solr so far? I maintain that plugin, so I'll help debug any issues you run into for that.

**Comment by jbob182** [comment] 2015-07-14 23:28
We've installed solr and gave it a shot and it is much faster. However, it still lacks. I had some developers and moderates try finding some recent threads and they were unable to. Even searching the exact title of a thread yields poor results.

**Comment by psychobunny** [comment] 2015-07-15 04:00
I'm interested in improving our search. I think the only way we can do this properly is to build test cases against expected results

ex. 

I search for "results" but I did not get posts that only had the keyword "result" -- **fail**

If anybody would be interested in starting a compilation of pass/fail possibilities I suggest we start a brand new meta issue on search improvements and close this one. 

Then we can write tests against the above and build better search functionality. The test runner should probably insert for ex. 100 posts with unique-ish lorem ipsum wording into the database, search against it, and make sure the results are as expected.

One overbearing issue at the moment is that our test runner does not support testing plugins. :X

**Comment by julianlam** [comment] 2015-07-15 14:36
:+1:

**Comment by FokkeZB** [comment] 2015-07-16 17:56
@jbob182 thanks for checking out Solr. Speed isn't our most concern, but accuracy is. Did anyone found the elasticsearch plugin to be better as it comes to this?

**Comment by julianlam** [comment] 2015-07-16 19:04
@FokkeZB @jbob182 Are you seeing search results missing topics when you've queried **the exact search term**? If so, then it is a bug. Let us know the post content, and the query.

Stemming/Lemmatization for Solr is not implemented, but I'm looking into it now.

**Comment by julianlam** [comment] 2015-07-16 20:12
Okay, so I've been playing around with some language detection and stemmer libraries for Node.js (`languagedetect` and `natural`, if you were wondering), and while the input text can be stemmed properly if a supported language is detected, I can't know for certain what language a user _conducting a search_ is using.

For example, `natural` ships with English, Russian, and Spanish stemmers. I can stem the input text (so things like `details` is truncated to `detail`), but when a search is conducted, I won't know to apply the proper stemmer since I don't know what language the query is conducted in.

So then we'd run into issues where, let's say, Spanish content wouldn't be searchable because the English-stemmed query wouldn't match any indexed items (as they've all been stemmed as Spanish).

**Comment by FokkeZB** [comment] 2015-07-17 18:42
@julianlam go ahead and try to reproduce some of the issues our users have been reporting here:
https://community.appcelerator.com/topic/2337/suspend-the-q-a-forums-now/2

But I think stemming is another worry while exact matches don't even seem to fully work atm. For example, I know there's posts complaining about search not working but they don't show up here:
https://community.appcelerator.com/search/search?in=posts

**Comment by julianlam** [comment] 2015-07-17 19:11
@FokkeZB Just ruling out indexing issues... on dbsearch, if you drop the index and re-index, does the search perform more accurately?

**Comment by wayneworkman** [comment] 2015-07-25 01:01
@psychobunny   Here is some test cases that I've been running. I'm going to provide you with the exact link to the articles that I'd like to see show up high in the search results, along with what I've been searching for to try to find them (simulating a user who is trying to solve a problem). 

Threads:

https://forums.fogproject.org/topic/4859/fog-bios-and-efi-coexistence
https://forums.fogproject.org/topic/4628/undionly-kpxe-and-ipxe-efi

Search terms I've used:

bios and uefi booting on the same network
bios and uefi booting same network
bios and uefi together
bios and uefi same lan
EFI and BIOS work at the same time
EFI and BIOS
Network booting EFI and BIOS at the same time
Network booting UEFI and BIOS together
old and new computers network booting at the same time
old and new computers coexisting
BIOS and EFI coexisting
Different boot files at the same time
DHCP give bootfile determined by client type


Now obviously, I got a little creative with some of those search terms, but I wanted to provide you with ample examples to think about. I feel like several of those terms should yield the aforementioned threads but they don't.

**Comment by jbob182** [comment] 2015-10-04 00:40
While this does not directly address the quality of results produced by the search algorithms, we have written our own search plugin. It bypasses Nodebb altogether and instead uses a Google CSE to retrieve the results. So far its been working quite nicely for us and our community.

**Comment by FokkeZB** [comment] 2015-10-04 06:03
That's also what we do now at community.appcelerator.com. Make sure you filter it to only show /topic or you will get posts on user pages as well.

**Comment by jacques-** [comment] 2016-04-23 07:13
Our forum is an internal one so we don't have the option of a google CSE based solution.

We are not having a problem of search not finding things when there are exact matches, but rather there are always some matches, even when there shouldn't be.

This seems to be happening more when search terms are very short acronyms like the EFI example posted above.

We have a technical forum, but a search for "zebra" returns a whole bunch of results...

Would a switch to solr change this?

**Comment by nodebb-misty** [comment] 2016-04-30 12:30
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*

**Closed by nodebb-misty** 2016-04-30 12:30 UTC
Labels: needs more info
