### ISSUE TITLE
Translations overwrite not working anymore.

### ISSUE THREAD

**Issue by Faianca** [NodeBB/NodeBB#5000] opened 2016-08-31 14:02 UTC
In the last nodebb 1.1.2 ( i had 1.0.0 ), i can not overwrite translations.

on my plugin.json i have "languages": "languages", which has languages/de/global.json.
On the request http://localhost:4567/language/de/global.json i can see the correct translations but they are not reflected on the frontend.

On 1.0.0 it overwrites perfect, but with the last version nothing happens.

**Comment by julianlam** [comment] 2016-09-01 13:06
@Faianca Does it happen on both cold load and ajaxify? (e.g. `F5` on a page vs browsing to it from another internal page)

**Comment by julianlam** [comment] 2016-09-01 13:07
Duplicate of #4982, it seems.

**Closed by julianlam** 2016-09-01 13:07 UTC

**Comment by Faianca** [comment] 2016-09-01 15:53
@julianlam Happens on both. It just can't overwrite anything.
