### ISSUE TITLE
Chat Window - Open to most recent

### ISSUE THREAD

**Issue by justinlosh** [NodeBB/NodeBB#2670] opened 2015-01-29 07:23 UTC
When you open expand a chat box to go to full screen (redirects to /chats/*username*) it shows the oldest messages. Can you set it so that on load, it automatically scrolls to the most recent messages?

**Comment by julianlam** [comment] 2015-02-02 00:34
Hi Justin, thanks for the report.

[This has been a part of NodeBB since last July](https://github.com/NodeBB/NodeBB/commit/a031bc272117b21f37f2ac3167bcef66d9da8ae7), are you not seeing this happening?

**Comment by justinlosh** [comment] 2015-02-02 00:38
No, I'm not seeing this happening. It scrolls to the bottom if you open the chat box, but when you click the button to take you to the full screen (/chats/%username), you have to scroll to the bottom.

**Comment by MegaGM** [comment] 2015-02-02 00:59
> it shows the oldest messages

I cannot reproduce this behavior. I always see newest.

**Comment by julianlam** [comment] 2015-02-02 01:01
Any js errors, @justinlosh ?

**Comment by justinlosh** [comment] 2015-02-02 01:04
@julianlam No js errors... I've just verified again, same issue.

**Comment by julianlam** [comment] 2015-02-02 01:30
Only reproducible on sidebars, should be fixed with latest commits.

**Closed** 2015-02-02 01:30 UTC
Labels: needs confirmation

**Comment by justinlosh** [comment] 2015-02-02 01:34
Awesome. Thanks!
