### ISSUE TITLE
Plugin-added localisations not working on server-side translation invocation

### ISSUE THREAD

**Issue by segura2010** [NodeBB/NodeBB#4982] opened 2016-08-26 19:21 UTC
Hi!

I have realized there are a problem with the translations..

In older versions of NodeBB we had user_mentioned_you_in translation (https://github.com/NodeBB/NodeBB/blob/v0.7.x/public/language/en_GB/notifications.json#L23), but in latests versions it has disappeared (https://github.com/NodeBB/NodeBB/blob/master/public/language/en_GB/notifications.json).

It is strange, because the web client works and load the translation (i dont know from where), but the plugins which use the translator (https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/translator.js) are broken (Pushbullet, Telegram..).

Is there any way to fix it?

**Comment by pichalite** [comment] 2016-08-26 19:37
mention language strings are now maintained in the mentions plugin https://github.com/julianlam/nodebb-plugin-mentions

**Comment by julianlam** [comment] 2016-08-26 19:52
@segura2010 In what way does the translation not work in Pushbullet?

As @pichalite says, the translation for mentions is handled in the mentions plugin now...

**Comment by julianlam** [comment] 2016-08-26 19:52
@yariplus did you run into something similar?

**Comment by jarey** [comment] 2016-08-26 19:55
@julian already reported this behaviour a while ago in two of the community threads.

**Comment by jarey** [comment] 2016-08-26 19:56
https://community.nodebb.org/post/50590

**Comment by yariplus** [comment] 2016-08-26 21:43
I did have an issue with translations, but it was fixed by adding `defaultLang` to plugin.json, this issue appears to be different.

**Comment by segura2010** [comment] 2016-08-27 08:40
@julianlam yes, the Pushbullet plugin doesnt work (http://i.imgur.com/Fu83Kyz.png).

So, the problem is that plugins doesnt have access to the other plugins translations. We need some easy way to access to the other plugins translations.

**Comment by barisusakli** [comment] 2016-08-27 11:37
That's weird, if a plugin adds a new translation key/value then it should become available to everyone is that not the case? @julianlam

**Comment by exomarty** [comment] 2016-08-28 22:16
Confirmed not working
Also with this kind of translations


[[groups:request.notification_text, daenick, Steam]]

**Comment by segura2010** [comment] 2016-09-01 11:21
Something new?

**Comment by julianlam** [comment] 2016-09-01 16:40
Can't repro what you guys are saying, though I may be doing it wrong?

```
require(['translator'], function(translator) {
  translator.translate('[[groups:request.notification_text, daenick, Steam]]', 'de', function(translated) {
    console.log(translated);
  });
});
```

Works as intended, outputs: `<strong>daenick</strong> möchte Mitglied von <strong>Steam</strong> werden.`

**Comment by julianlam** [comment] 2016-09-01 16:41
That one being a core string, here's a plugin string:

```
require(['translator'], function(translator) {
  translator.translate('[[notifications:user_mentioned_you_in, dragonfruit, asdf]]', 'de', function(translated) {
    console.log(translated);
  });
});
```

Which outputs: `<strong>dragonfruit</strong> erwähnte dich in <strong>asdf</strong>`

**Comment by julianlam** [comment] 2016-09-01 16:44
I think maybe you guys are saying that the translations are not loaded on server-side invocation of the translator? That does sound plausible... since at top @segura2010 mentioned that translations aren't working for Pushbullet/Telegram... hmmm

**Comment by segura2010** [comment] 2016-09-01 16:55
@julianlam yes, i mean the translation are not working server side

**Comment by jarey** [comment] 2016-09-01 16:56
Just if it somehow related to this. The problem i've found with translations i'm still debuggin (finding time for it) it is too server-side cause it has to do with translations not showinf propperly and falling to default en_GB on my plugin on a cold refresh. Maybe it has nothing to do with this issue, just wondering.

Also, my translation are plugin-exclusive. Maybe there's an issue involving the whole translation system server-side?

**Comment by julianlam** [comment] 2016-09-01 18:11
@Faianca, please see if this issue is resolved on the latest commits on `master`

**Comment by julianlam** [comment] 2016-09-01 18:12
@jarey That sounds like a separate issue, though hopefully the commit above fixes it.

**Comment by pichalite** [comment] 2016-09-01 23:16
getting error when opening composer
```
error: [translator] Could not load `markdown`: ENOENT: no such file or directory, open '/home/ubuntu/workspace/public/language/en_GB/markdown.json'. Skipping...
```

**Comment by Faianca** [comment] 2016-09-02 08:27
@julianlam i can confirm that it fixed for me on last master.

**Comment by julianlam** [comment] 2016-09-02 13:39
Seems I was just handling error states and invoking old code which wasn't required, seems fine to remove.

In any case, why am I fixing this when @pitaj wrote a new translator :rage2:

**Closed** 2016-09-02 13:39 UTC
Labels: bug
