### ISSUE TITLE
[BUG] No save button when editing profile 

### ISSUE THREAD

**Issue by UiharuKazari2008** [NodeBB/NodeBB#6343] opened 2018-03-06 04:31 UTC
<img width="1336" alt="screen shot 2018-03-05 at 23 30 39" src="https://user-images.githubusercontent.com/15165770/37014243-460ea8e4-20cd-11e8-8ac1-e98d7f52e5a3.png">

- **NodeBB version:** 1.7.5
- **NodeBB git hash:** 
87c5dd34ea0171ac295bbf3c8d73c68076bc5c57
- **Database type:** mongo
- **Database version:** 
v3.6.3
- **Exact steps to cause this issue:**
Go to profile
click the 3 dot menu, select edit profile
change something
no way to save it
- **What you expected:**
A save button
- **What happened instead:**
Theres no save button, no way for a used to update there profile after creation

**Comment by pitaj** [comment] 2018-03-06 04:33
That looks like a custom theme, have you tried it with Persona? I can't reproduce on community.nodebb.org

**Comment by UiharuKazari2008** [comment] 2018-03-06 04:37
Yes sir that is my current theme, everything i have done is in the custom css settings sense i dont want to muck around with themes

Heres my CSS
`.category > ul > li:not(.unread) h2 a { color: #fff; }
body { font-family: "Courier New", Courier, monospace; color: #ffffff; }
h1 small, .h1 small, h2 small, .h2 small, h3 small, .h3 small, h1 .small, .h1 .small, h2 .small, .h2 .small, h3 .small, .h3 .small { font-size: 40%; }
a:hover, a:focus { color: #85e9ff; }
a { color: #4db5c2; }
.breadcrumb { background-color: #012c52; }
.breadcrumb > .active { color: #ffffff; }
.nav-tabs a, .nav-pills a, .breadcrumb a, .pager a { color: #c9c9c9; }
.breadcrumb > li + li::before { color:#c9c9c9; }
.categories .description, .category .description, .subcategory .description { color: #5a8aa3; }
.categories .category-children small, .category .category-children small, .subcategory .category-children small { color: #5e95c1; }
.categories-title { color: #1ac4ed; font-size: 30px; font-style: italic; }
h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 { font-family: "Courier New", Courier, monospace; }
.alert-warning { background-color: #e17800; }
a.permalink, a.permalink:active, a.permalink:focus, a.permalink:hover { color: #ff9f8d; } 
.topic h1 .topic-title { color: #05c0ff; font-style: italic; }
.form-control { display: block; color: #ff0f19; background-color: #000000; border-bottom: 1px solid #8f0703; border-top: 0px; border-left: 0px; border-right: 0px; border-radius: 8px; }
.composer .title-container .title { color: #000; background-color: #fff; border-bottom: 1px solid #8f0703; border-top: 0px; border-left: 0px; border-right: 0px; border-radius: 8px; }
.composer .write { color: #000; }
.navbar-default .navbar-nav > li > a { color: #ff0dbf; }
.header .forum-logo {  max-height: 45px; }`

**Comment by pitaj** [comment] 2018-03-06 04:39
Have you tried disabling custom CSS? Please do if you haven't. (Just in case, you can switch the toggle at the bottom, you don't need to delete your CSS).

**Comment by UiharuKazari2008** [comment] 2018-03-06 04:42
I disabled custom css, and set the skin to something else (I was using cyborg as my base) and still no dice. Could it be a plugin? I don even see it in the source.
<img width="1419" alt="screen shot 2018-03-05 at 23 41 35" src="https://user-images.githubusercontent.com/15165770/37014465-df780114-20ce-11e8-8fe0-732722fd06b0.png">

**Comment by pitaj** [comment] 2018-03-06 04:56
Can you try running `./nodebb build` and restarting? If that doesn't work, then I would try disabling plugins.

**Comment by UiharuKazari2008** [comment] 2018-03-06 05:04
Tried that, I uninstalled all my 3rd party plugins besides a sound pack, here is what i have left. I think thats all that was standard?
<img width="591" alt="screen shot 2018-03-06 at 00 03 10" src="https://user-images.githubusercontent.com/15165770/37014936-e63b663c-20d1-11e8-907d-20d6e1444672.png">
<img width="467" alt="screen shot 2018-03-06 at 00 03 17" src="https://user-images.githubusercontent.com/15165770/37014937-e64954d6-20d1-11e8-845b-d70769787290.png">

**Comment by barisusakli** [comment] 2018-03-06 15:20
You can check the contents of `/build/public/templates/account/edit.tpl` it should have the save button. `<a id="submitBtn" href="#" class="btn btn-primary">[[global:save_changes]]</a>` If it's not there it might have been removed from the theme tpl file or it is being removed by something else.

**Comment by UiharuKazari2008** [comment] 2018-03-06 15:32
Yes i see it there at line 250

**Comment by UiharuKazari2008** [comment] 2018-03-06 15:52
Ok now for some reason the button has returned..... Why, I have no clue i have not done anything yet just checked now
<img width="1202" alt="screen shot 2018-03-06 at 10 51 31" src="https://user-images.githubusercontent.com/15165770/37042427-6bc03670-212c-11e8-912b-369a54e0c7f4.png">

**Comment by pitaj** [comment] 2018-03-06 16:23
Odd. 

Well, I'll close this. Let me know if you run into it again.

**Closed by pitaj** 2018-03-06 16:23 UTC
Labels: needs confirmation, needs more info
