### ISSUE TITLE
ACP client javascript error: dashboard.js "cannot reat property data of null"

### ISSUE THREAD

**Issue by jarey** [NodeBB/NodeBB#5346] opened 2017-01-06 19:14 UTC
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
**Clean install of v1.4.2.
C:\Users\jose\Documents\GitHub\nodebb [v1.x.x ≡]> git rev-parse HEAD
b1b9174479fa5806b4b30276ae3e10027d2074f5**

* Database (mongo or redis) and it's version : Mongo 3.2 (windows)
* Exact steps to cause this issue
    1. Logged into the formum for first time.
    2. Go to ACP.
    3. Go to plugins, searched one installed plugin.
    4. Clicked on ACTIVATE the plugin. Nothing happens (crash on console).

```
dashboard.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:360 Uncaught TypeError: Cannot read property 'data' of null
    at updateRegisteredGraph (dashboard.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:360)
    at p.Admin.updateRoomUsage (dashboard.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:115)
    at p.onack (acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:6)
    at p.onpacket (acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:6)
    at d.<anonymous> (acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:6)
    at d.r.emit (acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:5)
    at d.ondecoded (acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:4)
    at f.<anonymous> (acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:6)
    at f.n.emit (acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:4)
    at f.add (acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:4)

acp.min.js?v=b23cebad-c107-4b3d-b07c-12cb10dd9c11:11 [ajaxify /admin/extend/plugins] Time elapsed: 1456ms
```
* What you expected
    * Plugins gets activated.
* What happened instead
    * App crashed client side.

I have seen this error when managin users too (creating an user and giving him admin permissions). Seems to happen the first time ACP is accessed. The error doesn't reproduce after the reload of the page.

Kind of confused that this happens on ACP on a stable version. Just pulled last code form v.1.x.x., deleted my DB, executed ./nodebb setup to get 1.4.2 clean install working. After that i see the error described.

Thank you!

**Comment by julianlam** [comment] 2017-01-12 18:50
@jarey Does this happen on `master`?

**Comment by psychobunny** [comment] 2017-01-12 19:08
> Seems to happen the first time ACP is accessed. The error doesn't reproduce after the reload of the page.

This specifically happens to me, on `develop`. Doesn't seem to break anything though for me

**Comment by psychobunny** [comment] 2017-01-13 05:41
^ @jarey can you confirm your specific issue is fixed, this commit is on the latest `develop` branch. I think that potentially you have another issue altogether and may be thinking this is due to the above error (which I managed to repro, and is now fixed). Let me know :)

**Comment by julianlam** [comment] 2017-01-20 17:37
May be fixed via 97fe86c91685dae39786a09796a24f7c90645c9a, please report otherwise @jarey

**Comment by pichalite** [comment] 2017-01-20 18:43
It's not fixed @julianlam. I just got this error on latest master. Using commit 694f2382bfd8b9d45d7619faff1011d5c80630f7

**Comment by jarey** [comment] 2017-01-20 20:31
Just re-tested running master on commit 604206843e3998924d05e3d1d51b620030ad3aa6 and it replicates:

Error is happening at this point of the code:

	function updateRegisteredGraph(registered, anonymous) {
		**graphs.registered.data**.datasets[0].data[0] = registered;
		graphs.registered.data.datasets[0].data[1] = anonymous;
		graphs.registered.update();
	}


Fresh install, running ./nodebb dev ; first login ever on the app, entered ACP right after login. Error happened.

![image](https://cloud.githubusercontent.com/assets/5025224/22164467/9cf032b2-df57-11e6-8eab-e27bc248b737.png)

**Comment by jarey** [comment] 2017-01-20 20:59
I think that the order of invocation in Admin.init (dashboard.js L38) should change, so

`socket.emit('admin.rooms.getAll', Admin.updateRoomUsage);`

should be called at the end of the function, after `setupGraphs();`, or just `setupGraphs();` get called just at the beging of the function right before `socket.emit('admin.rooms.getAll', Admin.updateRoomUsage);`

Don't know if there's some other implication in the change with other functionality since i don't really know well how the dashboard code is managed.

**Comment by jarey** [comment] 2017-01-20 21:32
If `setupGraphs()` is called before `socket.emit('admin.rooms.getAll', Admin.updateRoomUsage);` on Admin.init the problem is that the translations inside `setupGraphs` for all admin keys that are performed on the method, are **slowe**r than the paralell code that gets to execute the `socket.emit `so at the end `Admin.updateRoomUsage` is called before the data initialation and the error keeps ocurring.

 I don't see how to solve it right now without refactoring a bit.

Hope the information can help on resolution.

**Comment by pitaj** [comment] 2017-01-21 21:44
Thanks, @jarey! I am unable to reproduce the issue in the first place, but I'm sure @psychobunny or @julianlam can fix this with that information.

**Comment by nodebb-misty** [comment] 2017-01-29 08:30
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*

**Comment by pichalite** [comment] 2017-01-29 19:04
This needs a `bug` label not `needs confirmation`.

**Comment by julianlam** [comment] 2017-03-14 13:53
@jarey can you confirm that this is fixed with the above commit?

**Closed** 2017-03-14 13:52 UTC
Labels: bug

**Comment by jarey** [comment] 2017-03-15 22:17
Sorry but i've been very busy and haven't got the time to re-test this. Now i'm starting vacation, so i would be able to re-test this when i'm back ~=31/03. So if anyone can re-test before should be awesome.

If not i would test if it is fixed at that date.

Regards.
