### ISSUE TITLE
Select a Skin in Profile on PC

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3868] opened 2015-11-10 20:06 UTC
How to reproduce:
1/ Go to Profile
2/ Select Settings
3/ Change layout using "Select a Skin" (from default to any other)

Issues:
1/ Profile menu not fully visible and in wrong place (see attached image)
2/ https vs http prevents a page refresh (http detected as unsecure)
3/ From time to time closing a tab and opening a new one needed to get a new look/skin

Opera beta 33.0.1990.35, Windows 7, HD display

![profilemenu](https://cloud.githubusercontent.com/assets/11160550/11073997/79fe0206-87ed-11e5-8114-b4e142b93d4e.jpg)

**Comment by barisusakli** [comment] 2015-12-18 12:11
Seems to be fixed on https://community.nodebb.org/

**Closed by barisusakli** 2015-12-18 12:11 UTC

**Comment by samhax** [comment] 2016-06-16 16:29
I can confirm this happens in 1.0.3.
