### ISSUE TITLE
Add LRU cache to registration queue

### ISSUE THREAD

**Issue by ProjectInfinity** [NodeBB/NodeBB#4468] opened 2016-03-25 12:42 UTC
When attempting to view the registration queue NodeBB doesn't load it. Instead it just infinitely attempts to load it, any other page works fine.The logs do not reveal any errors either.

We're on master branch commit 691802efadcc0dcdb249649b02f777f34171e1aa

**Comment by julianlam** [comment] 2016-03-25 22:52
I can't reproduce this issue, can you please let us know the values of the following database commands?

`db.objects.find({ _key: /registration:queue:name/ }).pretty();`

and

`db.objects.find({ _key: "registration:queue" }).pretty();`

**Comment by ProjectInfinity** [comment] 2016-03-25 22:53
We're using redis. Isn't that mongodb syntax?

**Comment by julianlam** [comment] 2016-03-25 23:12
Sure is -- for Redis:

`KEYS registration:queue:*` and `ZRANGE registration:queue 0 -1 WITHSCORES`

**Comment by ProjectInfinity** [comment] 2016-03-26 15:38
for the first command:
http://pastebin.com/raw/SLZnzG7E
and the second:
http://pastebin.com/raw/MAs0KwaE

Thanks.

**Comment by julianlam** [comment] 2016-03-26 15:43
Whoa, that's a long queue. Did this happen over time and get slower and slower?

**Comment by ProjectInfinity** [comment] 2016-03-26 15:45
No, pretty much overnight. It's always been fairly snappy but then it just stopped loading. It does however say that there's 10 registrations in the queue plus some additional single entries in the notification bar.

**Comment by julianlam** [comment] 2016-03-26 17:28
Were there always this many users in the queue?

**Comment by ProjectInfinity** [comment] 2016-03-26 17:31
Probably not. There was around 20-30 people in the queue before it stopped
loading. But I've never displayed the queue through redis before. More are
added to the queue as people register the past 3 days.

**Comment by julianlam** [comment] 2016-03-26 17:36
I see -- can you navigate to `/api/admin/manage/registration`, and see if the page hangs as wel?

**Comment by ProjectInfinity** [comment] 2016-03-26 17:39
Yes that also seems to hang.

**Comment by julianlam** [comment] 2016-03-26 17:40
Thanks. Will let you know what I find.

**Comment by julianlam** [comment] 2016-03-26 17:42
@ProjectInfinity Any chance I can get a copy of your Redis database for testing?

**Comment by julianlam** [comment] 2016-03-26 18:05
Committed some tweaks in 5705681aa050115c57a3fed2b35cfd7b5af21626, can you update to latest `master` and try again?

**Comment by ProjectInfinity** [comment] 2016-03-26 20:05
Hi, I'm afraid even with the tweaks from 5705681aa050115c57a3fed2b35cfd7b5af21626 it still hangs.

Is there a private way I may share the database dump file without publicly posting it?

**Comment by julianlam** [comment] 2016-03-26 20:08
Sure, you can email me the dump (link to a Dropbox share is best) @ julian@nodebb.org

**Comment by ProjectInfinity** [comment] 2016-03-26 20:22
Sent.

**Comment by ProjectInfinity** [comment] 2016-03-28 20:07
Any progress on this?

**Comment by julianlam** [comment] 2016-03-28 22:33
Haven't found time to look into this quite yet, uploading the db now (you can remove it from the owncloud instance now)

**Comment by julianlam** [comment] 2016-03-28 23:56
The page loads fine, it just has too many users right now so it's quite slow. Give it a good 5 minutes, and I've added a cache now, so subsequent loads will be faster.

**Comment by julianlam** [comment] 2016-03-28 23:56
5e3a114

**Comment by barisusakli** [comment] 2016-03-29 06:53
Will add pagination

**Closed** 2016-03-29 08:25 UTC
Labels: enhancement

**Comment by ylxdzsw** [comment] 2018-08-06 15:01
Hi, I have the same problem in v1.10.1, exactly the same symptom: every page fine except `/admin/manage/registration` hang.

My outputs of the commands in the first comment are

```
> use nodebb
switched to db nodebb
> db.objects.find({ _key: /registration:queue:name/ }).pretty();
{
        "_id" : ObjectId("5b508d121d5237591417518b"),
        "_key" : "registration:queue:name:ylxdzsw",
        "email" : "ylxdzsw@gmail.com",
        "hashedPassword" : "$2a$12$rNfOWzdcVtSAafCKLA2NzubzgbBqVS/3x6sXg7giz8iVtoY******",
        "ip" : "210.140.75.*",
        "username" : "ylxdzsw"
}
> db.objects.find({ _key: "registration:queue" }).pretty();
{
        "_id" : ObjectId("5b508d121d5237591417518e"),
        "_key" : "registration:queue",
        "value" : "ylxdzsw",
        "score" : 1532005650112
}
```

I found some strange log in `logs/output.log`

```
2018-08-06T14:19:22.655Z [13105] - error:  message=connect ETIMEDOUT 192.124.249.*:80, stack=Error: connect ETIMEDOUT 192.124.249.*:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14), errno=ETIMEDOUT, code=ETIMEDOUT, syscall=connect, address=192.124.249.*, port=80
2018-08-06T14:24:56.351Z [13105] - error:  message=connect ETIMEDOUT 192.124.249.*:80, stack=Error: connect ETIMEDOUT 192.124.249.*:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14), errno=ETIMEDOUT, code=ETIMEDOUT, syscall=connect, address=192.124.249.*, port=80
```

There are a lot of the same records and they are related to the problem -- every time I open `/admin/manage/registration` there grows one more that record. However, `192.124.249.*` is not my IP. I didn't even see it before. I can't find that IP in other files in the `nodebb` folder or my nginx config.

The final state of hanging for several minutes is either
![default](https://user-images.githubusercontent.com/7145046/43723011-3b780ac2-99c9-11e8-83bd-01ffe88df804.PNG)
when open from other ACP pages, or
![2](https://user-images.githubusercontent.com/7145046/43723319-f117fa90-99c9-11e8-9190-3b1f1513f57b.PNG)
when open from URL directly.
