### ISSUE TITLE
User online presence seems to go offline at times for no reason

### ISSUE THREAD

**Issue by jeffbski** [NodeBB/NodeBB#4123] opened 2016-01-28 20:28 UTC
I have noticed that the user online presence loses its state at times, so an active user appears offline.

Sometimes it works properly and others it seems to go offline without any help.

I have chrome dev tools open I can see that the web socket connection is still alive and well and receiving events, but both myself and other users report the online status going off even while we are in the middle of chatting.

I also started getting email and sound notifications for new chats while I am still in the chat, so I know the state is getting messed up for some reason. 

I haven't figured out if anything in particular causes it, but I know I am not dropping web sockets, the channel is up and solid.

**Comment by barisusakli** [comment] 2016-02-01 17:42
Is nodebb running as a single process? What version is it happening on?

**Comment by jeffbski** [comment] 2016-02-01 18:30
yes, running as a single process. 

I am using a fairly recent commit off of master 4440865ec41a0d16b8a080b7dba9f8e53de5aea9

My web sockets appear solid, so I can't figure out why this is happening.

**Comment by barisusakli** [comment] 2016-02-01 18:36
Which part of nodebb are you using to check the user's online status? The online check was changed sometime ago to not use socket.io, a user is considered online if they have ajaxified in the past 5 mins or made a post.

**Comment by jeffbski** [comment] 2016-02-01 18:50
I was just looking at the user's page to monitor who is active.

I'll keep the criteria in mind for how it determines a user being online, but several times when I was in an active chat with a person (back and forth posting)and all of a sudden it must have considered me offline since it started giving me the sound notifications and sending me emails halfway through the chat (which shouldn't have happened when I am online). My friend then mentioned that it was showing me as offline which he found odd since we were actively chatting.

**Comment by pichalite** [comment] 2016-02-01 18:58
based on @barisusakli's comment "a user is considered online if they have ajaxified in the past 5 mins or made a post", looks like it's working as designed. When you are on the chat page, you are not ajaxifying or making a post.

I think this case (user sends a chat message) needs to be added to the user online check.

**Comment by barisusakli** [comment] 2016-02-01 18:59
Yeah users should be marked as online when they send a chat message, adding that now.

**Closed** 2016-02-01 19:09 UTC
Labels: bug

**Comment by jeffbski** [comment] 2016-02-01 19:46
Thanks!
