### ISSUE TITLE
Topic titles don't disappear on navigating away from a topic

### ISSUE THREAD

**Issue by jaloopa** [NodeBB/NodeBB#5778] opened 2017-06-26 15:34 UTC
- **NodeBB version:** whatever what.thedailywtf.com is on
- **Database type:** mongo
- **Exact steps to cause this issue:**
    1. enter a topic
    2. go back to a topic list thread, e.g. by clicking the unread icon or the site logo
- **What you expected:**
The navigated to page should show as expected with no topic title, as you're not in a topic
- **What happened instead:**
![image](https://user-images.githubusercontent.com/3093252/27547261-540e61c0-5a8d-11e7-9e39-f251d7e47b10.png)

The title sticks around in other threads and pages until the tab is refreshed

**Comment by barisusakli** [comment] 2017-06-26 15:42
Works for me on https://what.thedailywtf.com.

**Comment by jaloopa** [comment] 2017-06-26 15:46
I did notice it doesn't happen if you go back to `?logged in=true`. 

The bug still happens for me when logged out. I have confirmed it on chrome for android and Windows 7, and opera on Windows 10

**Comment by pitaj** [comment] 2017-06-26 19:43
Do you have a skin or something? what.thedailywtf looks nothing like that for me.

**Comment by pauljherring** [comment] 2017-06-27 09:47
> what.thedailywtf looks nothing like that for me.

One of the more garish themes no doubt. My reproduction with minimal additional CSS (the cause of the [] in my screenshots below..)

Click the 'Home' Icon (the face) - 

![image](https://user-images.githubusercontent.com/3939886/27581411-8d297506-5b25-11e7-8ea5-98e54705acdb.png)

Click one of the threads

![image](https://user-images.githubusercontent.com/3939886/27581436-9f68d400-5b25-11e7-86b7-05041d7af820.png)

Click the Home icon again - note that the thread title from the previous step is still present:

![image](https://user-images.githubusercontent.com/3939886/27581472-b74e08ec-5b25-11e7-99a8-10fe029806e5.png)

**Comment by pichalite** [comment] 2017-06-27 15:41
Default theme (persona) doesn't display topic title in header. I believe this is a customization on tdwtf and needs to be fixed on their side.

**Comment by pauljherring** [comment] 2017-06-27 15:48
Hmm - I'll pass it back.

**Comment by pauljherring** [comment] 2017-06-28 10:32
Close/reject please - confirmed to be a local issue.

https://github.com/boomzillawtf/tdwtf/pull/31

**Closed** 2017-06-28 11:11 UTC
