### ISSUE TITLE
notifications merge with the newest data, which is bad in some cases

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4610] opened 2016-05-09 02:03 UTC
For example, notifications for "users have posted replies to [topic]" should probably be merged with the oldest URL because a user watching a topic probably wants to read it in order.

ref: apapadimoulis/what-bugs#118
/cc @pauljherring

**Comment by julianlam** [comment] 2016-05-09 14:32
Duplicate of #4469, let me know if I am mistaken @BenLubar :smile:

**Closed by julianlam** 2016-05-09 14:32 UTC

**Comment by BenLubar** [comment] 2016-05-09 14:50
Ah, my mistake.
