### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by patatetom** [NodeBB/NodeBB#4743] opened 2016-06-08 12:22 UTC
hi,
I'm behind a proxy that only support http or https scheme, and git scheme is used for cloning  reCAPTCHA, so installation failed.
regards.

**Comment by julianlam** [comment] 2016-06-08 12:24
Cloning recaptcha? We don't do this directly, possibly @akhoury can help?

**Comment by patatetom** [comment] 2016-06-08 12:28
I'm trying to bypass with manual installation :
_npm install simple-recaptcha-new_
but error still remain : 
_npm ERR! Command failed: git clone --template=/home/nodebb/.npm/_git-remotes/_templates --mirror git://github.com/wzrdtales/simple-recaptcha.git /home/nodebb/.npm/_git-remotes/git-github-com-wzrdtales-simple-recaptcha-git-v1-0-0-ce1caeab_

**Comment by julianlam** [comment] 2016-06-08 12:29
It looks like you don't have git installed perhaps... I cannot tell from the error.

Nevertheless this is not a NodeBB package and so is not a bug. Sorry about that.

**Comment by patatetom** [comment] 2016-06-08 12:33
git is installed and proxies are configured : _git clone -b v1.x.x https://github.com/NodeBB/NodeBB.git nodebb_ is ok ;-)
but with _npm install_ command, an error occurs when _git clone git://..._ is used and this is in the nodebb install procedure...

**Comment by julianlam** [comment] 2016-06-08 12:36
My bad. I'm thinking perhaps it is a dependency that requires it. You may have to send that one upstream as it is not a direct dependency of ours...

**Comment by patatetom** [comment] 2016-06-08 12:40
the string "git://github.com/wzrdtales/simple-recaptcha.git" is found in nodebb-plugin-spam-be-gone/0.4.6/package/package.json and registry.npmjs.org/nodebb-plugin-spam-be-gone/.cache.json

**Comment by julianlam** [comment] 2016-06-08 12:41
Thanks for doing this legwork :smile:

Perhaps the package is published to npm now and can be directly downloaded from npm instead of via git

**Comment by patatetom** [comment] 2016-06-08 12:49
I _sed_ ('s;git://github;https://github;g') on these two files and restart _npm install_ and this is **ok** now :-)

**Comment by akhoury** [comment] 2016-06-08 15:18
yea sorry, you're right, it's this [line](https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/6b33cec66def313b10ab2c1522c380de93e00ab5/package.json#L32) - and @julianlam no it hasn't, the PR is still pending

https://github.com/zemirco/simple-recaptcha/pull/2

**Comment by akhoury** [comment] 2016-06-08 15:20
actually  it is published, lol, I'm an [idiot](https://github.com/zemirco/simple-recaptcha/pull/2#issuecomment-72275048) - i will make the switch for real this time.  thanks @patatetom 
https://github.com/np-maintain/simple-recaptcha-new

I'd close this bug here, I opened the one in the spam-be-gone project
https://github.com/akhoury/nodebb-plugin-spam-be-gone/issues/48

**Closed** 2016-06-09 11:08 UTC
Labels: needs more info
