### ISSUE TITLE
NodeBB 0.9.1 won't launch because of outdated lavender

### ISSUE THREAD

**Issue by edasque** [NodeBB/NodeBB#3921] opened 2015-12-02 15:42 UTC
Yet I have the latest:
![synology diskstation - ocho](https://cloud.githubusercontent.com/assets/219187/11535252/13e198d4-98e1-11e5-87ec-57bbe42d8f5c.png)
![synology diskstation - ocho](https://cloud.githubusercontent.com/assets/219187/11535271/2a7d2fe0-98e1-11e5-8397-af03bacf1f8f.png)
![synology diskstation - ocho](https://cloud.githubusercontent.com/assets/219187/11535306/48ab8bce-98e1-11e5-82f0-83528cd162d0.png)

I can't launch 0.9.1 (and I don't think I can revert now).

**Comment by julianlam** [comment] 2015-12-02 15:44
Re-published v3.0.2 of Lavender, pull and give it a try?

**Comment by edasque** [comment] 2015-12-02 15:46
Does 0.9.1 require a specific version of lavender?

**Comment by edasque** [comment] 2015-12-02 15:51
Still happening with 3.0.2. I am at my wits ends. Must be something silly.

**Comment by julianlam** [comment] 2015-12-02 15:53
While I don't recommend going into production like this, after [this line](https://github.com/NodeBB/NodeBB/blob/master/src/meta/dependencies.js#L30), add `return next(true);`

That should get you running in the meantime.

**Comment by edasque** [comment] 2015-12-02 15:58
That didn't work

![synology diskstation - ocho](https://cloud.githubusercontent.com/assets/219187/11535838/ae98ed44-98e3-11e5-89fb-9c9542ecbb95.png)

**Comment by julianlam** [comment] 2015-12-02 16:04
You can go back to 0.9.0... there weren't any updates to the schema. Just check out v0.9.x and give it a try (might need to do a `./nodebb upgrade` though)

**Comment by edasque** [comment] 2015-12-02 16:08
All right but you do know where the regression comes from?

**Comment by julianlam** [comment] 2015-12-02 17:15
At this point in time, I do not.

**Comment by edasque** [comment] 2015-12-03 02:18
Unfortunately going back to 0.9.0 seems difficult because it is pulling the latest nodebb-plugin-composer-redactor which doesn't work with 0.9.0 anymore. There isn't a tag or version for it so I'll try to pull a specific commit.

**Comment by edasque** [comment] 2015-12-03 14:41
I did pull an earlier commit and nodebb-plugin-composer-redactor works with 0.9.0.

**Comment by julianlam** [comment] 2015-12-04 16:32
@edasque I cannot reproduce this issue... uninstalled lavender, ran `./nodebb upgrade`, and then `node loader.js --no-daemon --no-silent` and NodeBB started up just fine.

**Comment by edasque** [comment] 2015-12-04 16:44
I reproduced it a few times. Are you using 4.2.x? My npm is 2.14.7

**Comment by sjennison** [comment] 2015-12-07 07:56
@julianlam this happened on the server I just set up too (brand new clean NodeBB install). I fixed it by manually npm install-ing the required version

**Comment by sjennison** [comment] 2015-12-07 07:57
Should've mentioned - Ubuntu install, followed the instructions to the letter. I can probably spin up a VM for repro if you want

**Comment by zombiefredrik** [comment] 2015-12-09 15:17
Same here on clean install. 
`[outdated] nodebb-theme-lavender installed v3.0.2, package.json requires 3.0.1`
Fixed by adding ^ to package.json 
`"nodebb-theme-lavender": "^3.0.1",`

**Comment by julianlam** [comment] 2015-12-09 15:18
Clean install on v0.9.x? Does it install fine on `master`?

**Comment by zombiefredrik** [comment] 2015-12-09 15:24
Seems to work fine on `master`

**Comment by edasque** [comment] 2015-12-09 21:44
I does seem to be a problem on 0.9.1 for other people.

**Comment by julianlam** [comment] 2015-12-10 20:40
If this is resolved in latest `master`, then when we launch v0.9.2 this will be resolved.

**Closed by julianlam** 2015-12-10 20:40 UTC
Labels: needs confirmation
