### ISSUE TITLE
Can't stop dragging widget

### ISSUE THREAD

**Issue by Firelad97** [NodeBB/NodeBB#3183] opened 2015-05-25 07:53 UTC
Without development mode, I can drag and drop widgets, but when in development mode, I can't stop dragging. It is stuck on mouse.

EDIT: Just turned off development mode and still can't stop dragging widget.

**Comment by psychobunny** [comment] 2015-05-29 19:54
Is there any errors in the console when you start dragging?

**Comment by Firelad97** [comment] 2015-05-29 23:18
Sorry, it was an issue with Openshift. Might because of outdated NodeJS and database. I'm upgrading both and sees what will happen.

**Comment by psychobunny** [comment] 2015-05-31 02:07
Cool, let me know if it still persists. I couldn't reproduce - closing for now

**Closed by psychobunny** 2015-05-31 02:07 UTC
