### ISSUE TITLE
Can you schedule a reply post?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#9817] opened 2021-09-21 11:36 UTC
Apologies if this issue should be raised on nodebb-composer-default plugin issue page. Let me know if you want me to post there instead.

I was wondering with the schedule post functionality if you can schedule a post that isn't a main post of a topic? Looking at the code (and I might have missed something) it appears that the Clock Icon for scheduling shows on the composer templates on replies but the timestamp isn't sent in a post reply.

https://github.com/NodeBB/nodebb-plugin-composer-default/blob/a25f6644c68bf2a63e0ef40dcb9f5b82e359c2c9/static/lib/composer.js#L476-L477

https://github.com/NodeBB/nodebb-plugin-composer-default/blob/4da651eb85ff5688d280c436a648e883fdf88959/static/templates/composer.tpl#L50-L52

https://github.com/NodeBB/nodebb-plugin-composer-default/blob/d26781e0f8515a9b9e6636d7b71f1d55d500ad04/static/lib/composer.js#L712-L720

Should the icon be hidden on replies or the timestamp sent with reply data?

**Comment by barisusakli** [comment] 2021-09-21 16:58
Replies shouldn't show the schedule button, should be fixed here https://github.com/NodeBB/nodebb-plugin-composer-default/commit/a25f6644c68bf2a63e0ef40dcb9f5b82e359c2c9

**Closed by barisusakli** 2021-09-21 16:58 UTC

**Comment by uplift** [comment] 2021-09-22 09:18
So I think this change (that I raised 😢) needs to be reverted - https://github.com/NodeBB/NodeBB/issues/9812 as this has broken what you intended and I misunderstood the flow and when schedule button should appear (originally thought it should show for replies). Reverting that change or adding isMain to first part fixes it again for me locally. Sorry for the confusion. 😞

**Comment by barisusakli** [comment] 2021-09-22 13:28
Well latest composer and core works as intended for me, as in no schedule button replies. Even with the change from #9812

**Comment by uplift** [comment] 2021-09-22 14:24
So on a topic page with privileges['topics:schedule'] === true.

Clicking the reply button would mean isEditing === false so !isEditing === true

So (privileges['topics:schedule'] && !isEditing) would be (true && true) so canSchedule = true meaning it should show the button.

Am I missing anything?

**Comment by barisusakli** [comment] 2021-09-22 14:32
@uplift you are right, clicking reply on a scheduled topic was broken, should be fixed with above commit.

**Comment by barisusakli** [comment] 2021-09-22 14:54
No worries, it was bug 👍🏼
