### ISSUE TITLE
Cannot scroll "Manage Group" dialog after "Change Icon" in ACP

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2754] opened 2015-02-23 04:22 UTC
Once the "Change Icon" is clicked, "Manage Group" modal is not scrollable anymore to hit Save.

**Comment by julianlam** [comment] 2015-02-23 14:19
Hm... this one *sounds* like a bootstrap bug. `Manage Group` is a modal, as is `Change Icon`, so perhaps when two modals stack, closing the top modal messes up the backdrop?

**Comment by julianlam** [comment] 2015-02-23 14:21
Please see twbs/bootstrap#15837

**Comment by julianlam** [comment] 2015-02-23 14:24
Ok, so that was closed as invaid, so the *proper* solution here is to refactor the interface to not use multiple modals.

**Comment by julianlam** [comment] 2015-02-23 14:25
I imagine the best course of action would be to move the group edit modal out to a separate page, similar to my plans for the category mgmt page.

**Comment by MegaGM** [comment] 2015-02-26 08:19
> move the group edit modal out to a separate page

:+1:

**Comment by yanickrochon** [comment] 2015-03-03 20:46
Just a note, since I cannot post this in the original issue that I have created (it is locked, and [referenced already](https://github.com/twbs/bootstrap/issues/15837)), I am posting my solution here, and the cause of the problem to easily solve your issue with Bootstrap.

The problem is the line

```js
that.$body.removeClass('modal-open');
```

In Bootstrap's modal module's `hideModal` function.

When closing any modal, check if there's an active modal being displayed. If so, reset the `modal-open` class. Like so :

```js
var activeModal = $('.modal.in', 'body').data('bs.modal');

if (activeModal) {
    activeModal.$body.addClass('modal-open');
    activeModal.enforceFocus();
    activeModal.handleUpdate();
}
```

Works like a charm for me.

**Comment by julianlam** [comment] 2015-03-03 20:49
Thanks for sharing your fix, @yanickrochon! I'll admit the *more correct* method of not using multiple modals is the correct course of action, but perhaps this will help others who stumble on the upstream issue.

**Comment by SeoRoman** [comment] 2015-03-13 20:42
@yanickrochon You sir... are a genius! Thank you so much! I was just looking for a fix to this issue as my create user box was scrollable, where as my "create role" (to add to my user list) was not... and thus I lost the ability to scroll the user form... This worked perfectly and was easy to implement :)

Thanks!

**Closed** 2015-06-22 17:10 UTC
Labels: bug, low priority

**Comment by 1Rhino** [comment] 2016-03-22 08:10
@yanickrochon Thank you. You saved my life! :+1:
