### ISSUE TITLE
Mention in deleted topic

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4263] opened 2016-02-25 20:55 UTC
https://community.nodebb.org/topic/7949/reply-as-topic-reg/4

1) new account Ngô (test user),
2) mentioned Ngô in deleted topic (main account),
3) Ngô alerted (see below).

![ngo](https://cloud.githubusercontent.com/assets/11160550/13334079/70d0281e-dc0a-11e5-83ea-241238eb8586.jpg)

**Comment by psychobunny** [comment] 2016-02-26 04:18
Only mods / admins can reply to a deleted topic... this really isn't a major issue I think, because I'm not sure why an admin would delete a topic and then reply and mention someone. Let me know if I had missed a use-case, will re-open, thanks

**Comment by pichalite** [comment] 2016-02-26 04:41
@psychobunny OP can reply to a deleted topic

**Comment by pichalite** [comment] 2016-02-26 04:43
This is what I see on the community. I am using a test user.

<img width="1208" alt="screen shot 2016-02-25 at 8 42 10 pm" src="https://cloud.githubusercontent.com/assets/10014774/13343311/4d1c2dfa-dc00-11e5-9674-b9f4fe21bc55.png">

I can reply even after I deleted the topic.

**Comment by psychobunny** [comment] 2016-02-26 04:44
So maybe the issue is that OP should not be able to reply to a deleted topic?

**Comment by pichalite** [comment] 2016-02-26 04:48
Yeah I think so. In his first comment he said (main account) on point 2. I think he means his account nhl.pl on the community. He does all his testing on the community. Don't think he has mod capability.

**Comment by pichalite** [comment] 2016-02-26 04:52
Just thinking out loud... what would be the use case where the OP needs to reply to a deleted topic.

**Comment by psychobunny** [comment] 2016-02-26 05:08
I heard one use-case: as a private diary. I don't think that's a good enough idea, could better be done properly as a plugin.

I think this should be reopened as "don't allow anybody (even admins, because why?) to reply to deleted topics"

**Comment by barisusakli** [comment] 2016-02-26 07:48
Uh imo it should be fixed properly, ie dont sent mentions from topics if you don't have read permission on them

**Comment by psychobunny** [comment] 2016-02-26 07:56
I think you shouldn't be allowed to reply to a deleted topic, that was my original opinion

But you reassigned to yourself so :lalala: :p

**Comment by nhlpl** [comment] 2016-02-26 08:50
Sorry for a late reply, GMT+1 here.

Forum admins configure and use your software in many scenarios. My experience shows that similar "not a bug" thing can become a real issue.

Not talking about NodeBB (below)
For example. Now using a legacy forum software. After 8 years of use I have found a search related bug which allow guests to see deleted topics/posts in hidden category (trash can) added by banned user.

**Closed** 2016-02-26 12:21 UTC
Labels: bug
