### ISSUE TITLE
the master branch can not upload image

### ISSUE THREAD

**Issue by jinfagang** [NodeBB/NodeBB#7371] opened 2019-02-14 15:14 UTC
When open log, upload image trigger this error:

```
2019-02-14T15:10:17.612Z [4567/4889] - info: Routes added
2019-02-14T15:10:17.615Z [4567/4889] - info: NodeBB Ready
2019-02-14T15:10:17.620Z [4567/4889] - info: Enabling 'trust proxy'
2019-02-14T15:10:17.624Z [4567/4889] - info: NodeBB is now listening on: 0.0.0.0:4567
2019-02-14T15:11:11.986Z [4567/4889] - error: uncaughtException: Could not locate the bindings file. Tried:
 → /root/nodebb/node_modules/sharp/build/sharp.node
 → /root/nodebb/node_modules/sharp/build/Debug/sharp.node
 → /root/nodebb/node_modules/sharp/build/Release/sharp.node
 → /root/nodebb/node_modules/sharp/out/Debug/sharp.node
 → /root/nodebb/node_modules/sharp/Debug/sharp.node
 → /root/nodebb/node_modules/sharp/out/Release/sharp.node
 → /root/nodebb/node_modules/sharp/Release/sharp.node
 → /root/nodebb/node_modules/sharp/build/default/sharp.node
 → /root/nodebb/node_modules/sharp/compiled/11.9.0/linux/x64/sharp.node
 → /root/nodebb/node_modules/sharp/addon-build/release/install-root/sharp.node
 → /root/nodebb/node_modules/sharp/addon-build/debug/install-root/sharp.node
 → /root/nodebb/node_modules/sharp/addon-build/default/install-root/sharp.node
 → /root/nodebb/node_modules/sharp/lib/binding/node-v67-linux-x64/sharp.node
Error: Could not locate the bindings file. Tried:
 → /root/nodebb/node_modules/sharp/build/sharp.node
 → /root/nodebb/node_modules/sharp/build/Debug/sharp.node
 → /root/nodebb/node_modules/sharp/build/Release/sharp.node
 → /root/nodebb/node_modules/sharp/out/Debug/sharp.node
 → /root/nodebb/node_modules/sharp/Debug/sharp.node
 → /root/nodebb/node_modules/sharp/out/Release/sharp.node
 → /root/nodebb/node_modules/sharp/Release/sharp.node
 → /root/nodebb/node_modules/sharp/build/default/sharp.node
 → /root/nodebb/node_modules/sharp/compiled/11.9.0/linux/x64/sharp.node
 → /root/nodebb/node_modules/sharp/addon-build/release/install-root/sharp.node
 → /root/nodebb/node_modules/sharp/addon-build/debug/install-root/sharp.node
 → /root/nodebb/node_modules/sharp/addon-build/default/install-root/sharp.node
 → /root/nodebb/node_modules/sharp/lib/binding/node-v67-linux-x64/sharp.node
    at bindings (/root/nodebb/node_modules/bindings/bindings.js:124:9)

```

How should I repair this? The older version has no problem but layout are messed up

**Comment by pitaj** [comment] 2019-02-14 15:25
Try checking out this topic.

https://community.nodebb.org/topic/13455/image-upload-issues/

I'm gonna close this issue as it's a request for help, not a bug.

**Closed by pitaj** 2019-02-14 15:25 UTC
